#' @title Maximum Likelihood Estimation for Spatial Binary Probit Models with a Continuous Endogenous Regressor
#'
#' @description
#' Estimates a spatial autoregressive probit model with a continuous endogenous
#' regressor by maximum likelihood. The probability contribution of the binary
#' outcome is evaluated either by the Mendell--Elston (ME) approximation or by
#' recursive importance sampling (RIS).
#'
#' The latent-variable model is
#'
#' \deqn{
#' y^* = X\beta + WX\gamma + \lambda W y^* + \varepsilon,
#' }
#'
#' where \eqn{y = 1} if \eqn{y^* > 0} and zero otherwise. One continuous
#' regressor in the structural equation is allowed to be endogenous. Let
#' \eqn{x_e} denote this regressor. Its reduced-form equation is
#'
#' \deqn{
#' x_e = Z\pi + v,
#' }
#'
#' where \eqn{Z} contains the exogenous structural regressors and the excluded
#' instruments supplied by the user. Endogeneity is introduced through the
#' correlation between the structural disturbance and the reduced-form
#' disturbance:
#'
#' \deqn{
#' \mathrm{Corr}(\varepsilon, v) = \rho.
#' }
#'
#' Conditional on \eqn{v}, the spatial binary model has mean
#'
#' \deqn{
#' \mu =
#' (I - \lambda W)^{-1}
#' \left(
#' X\beta + WX\gamma + \frac{\rho}{\sigma_v}v
#' \right),
#' }
#'
#' and covariance matrix
#'
#' \deqn{
#' \Omega =
#' (1-\rho^2)
#' (I-\lambda W)^{-1}
#' (I-\lambda W)^{-T}.
#' }
#'
#' The joint likelihood combines the Gaussian likelihood of the reduced-form
#' equation for \eqn{x_e} with the multivariate normal probability associated
#' with the binary outcome.
#'
#' @name sbinary_iv_ml
#'
#' @param formula A symbolic description of the model of the form
#'   \code{y ~ x | wx | instruments}. The first right-hand side contains the
#'   structural regressors, including the continuous endogenous regressor. The
#'   second right-hand side contains variables whose spatial lags \eqn{WX}
#'   enter the structural equation. The third right-hand side contains the
#'   excluded instruments for the endogenous regressor. Use \code{| 0 |} in
#'   the second part when no spatially lagged regressors are included.
#'
#' @param data A \code{data.frame} containing the variables in the model.
#'
#' @param subset An optional vector specifying a subset of observations to be
#'   used in the estimation.
#'
#' @param na.action A function indicating what should happen when the data
#'   contain \code{NA}s.
#'
#' @param listw A spatial weights object of class \code{listw}, \code{matrix},
#'   or \code{Matrix}.
#'
#' @param endog Character string naming the continuous endogenous regressor.
#'   Only one continuous endogenous regressor is currently supported. The
#'   variable must enter directly in the first part of \code{formula} and
#'   cannot simultaneously appear in the \code{WX} part.
#'
#' @param method Character string indicating how the multivariate normal
#'   probability is evaluated. \code{"ME"} uses the Mendell--Elston
#'   approximation and \code{"RIS"} uses recursive importance sampling.
#'
#' @param varcov Character string indicating the matrix representation used in
#'   the probability calculations. \code{"invsigma"} uses the precision matrix,
#'   whereas \code{"sigma"} uses the covariance matrix. This argument refers to
#'   the Cholesky representation used internally and not to the estimator of
#'   the parameter variance-covariance matrix.
#'
#' @param ordering Character string specifying the ordering used in the
#'   multivariate normal probability evaluation. \code{"N"} uses the natural
#'   ordering and \code{"M"} uses an ordering based on marginal truncation
#'   probabilities. RIS currently supports only \code{"M"}. For ME with
#'   \code{varcov = "invsigma"} and \code{ordering = "M"}, an AMD permutation
#'   is additionally used to reduce fill-in in the sparse Cholesky
#'   factorization.
#'
#' @param R Integer. Number of antithetic simulation draws used when
#'   \code{method = "RIS"}. The default is \code{50}.
#'
#' @param seed Integer. Random-number seed used to generate the common
#'   antithetic draws for RIS. The global random-number state is restored after
#'   the draws are generated.
#'
#' @param start Optional vector of starting values on the structural parameter
#'   scale. Values must be supplied in the order
#'   \eqn{(\beta,\gamma,\lambda,\pi,\sigma_v,\rho)}, according to the columns
#'   generated by the model matrices. If \code{NULL}, starting values are
#'   constructed internally from a linear first-stage regression, a standard
#'   probit model, and a simple initial value for the spatial parameter.
#'
#' @param lambda.margin Numeric. Small positive margin used to keep the
#'   optimization interval for \eqn{\lambda} strictly inside the
#'   eigenvalue-based admissible parameter space.
#'
#' @param maxit Integer. Maximum number of iterations used by the
#'   \code{L-BFGS-B} optimizer.
#'
#' @param factr Numeric. Convergence control parameter passed to
#'   \code{optim(..., method = "L-BFGS-B")}.
#'
#' @param pgtol Numeric. Projected-gradient tolerance passed to the
#'   \code{L-BFGS-B} optimizer.
#'
#' @param hessian Logical. If \code{TRUE}, the observed Hessian is computed at
#'   the optimum using the final ordering held fixed. The resulting matrix is
#'   used by \code{vcov()} and \code{summary()} when
#'   \code{vce = "hessian"}, and is also required by the operational sandwich
#'   covariance estimator.
#'
#' @param print.init Logical. If \code{TRUE}, the starting values are printed
#'   both in optimizer coordinates and on the structural parameter scale.
#'
#' @param verbose Logical. If \code{TRUE}, information on the estimator,
#'   optimization convergence, log-likelihood, and Hessian diagnostics is
#'   printed.
#' 
#' @param x,object A fitted object of class \code{"binivml"}.
#' 
#' @param vce Covariance estimator. \code{"hessian"} (default) returns the
#'   inverse fixed-order observed Hessian. \code{"sandwich"} computes the
#'   operational model-based sandwich.
#'   
#' @param R Number of inner parametric simulations for the sandwich estimator.
#' 
#' @param seed Integer seed for the sandwich simulations.
#' 
#' @param digits Integer. The number of significant digits used when printing
#'   the model summary. 
#' 
#' @param ... Reserved for compatibility.
#'
#' @details
#'
#' Let
#'
#' \deqn{
#' A(\lambda) = I - \lambda W
#' }
#'
#' and let the reduced-form residual of the endogenous regressor be
#'
#' \deqn{
#' v = x_e - Z\pi.
#' }
#'
#' Under joint normality of the structural and reduced-form disturbances, the
#' structural disturbance can be written conditionally on \eqn{v} as
#'
#' \deqn{
#' \varepsilon
#' =
#' \frac{\rho}{\sigma_v}v
#' +
#' \sqrt{1-\rho^2}\eta,
#' \qquad
#' \eta \sim N(0,I).
#' }
#'
#' Hence, conditional on the endogenous regressor,
#'
#' \deqn{
#' y^*
#' =
#' A(\lambda)^{-1}
#' \left(
#' X\beta + WX\gamma + \frac{\rho}{\sigma_v}v
#' \right)
#' +
#' \sqrt{1-\rho^2}
#' A(\lambda)^{-1}\eta.
#' }
#'
#' The binary likelihood contribution therefore requires evaluation of an
#' \eqn{n}-dimensional normal probability. When \code{method = "ME"}, this
#' probability is approximated using the Mendell--Elston recursive
#' approximation. When \code{method = "RIS"}, it is evaluated using a
#' GHK-type recursive importance sampler with common antithetic draws.
#'
#' Two algebraically equivalent matrix representations are available.
#' With \code{varcov = "sigma"}, the recursion uses
#'
#' \deqn{
#' \Omega =
#' (1-\rho^2)A(\lambda)^{-1}A(\lambda)^{-T}.
#' }
#'
#' With \code{varcov = "invsigma"}, it uses the corresponding precision
#' matrix
#'
#' \deqn{
#' \Omega^{-1}
#' =
#' \frac{A(\lambda)'A(\lambda)}{1-\rho^2}.
#' }
#'
#' The estimator maximizes the joint log-likelihood
#'
#' \deqn{
#' \ell(\theta)
#' =
#' \ell_x(\pi,\sigma_v)
#' +
#' \log P(y \mid x_e,X,Z,W;\theta),
#' }
#'
#' where
#'
#' \deqn{
#' \theta =
#' (\beta,\gamma,\lambda,\pi,\sigma_v,\rho).
#' }
#'
#' Internally, \eqn{\sigma_v} and \eqn{\rho} are parameterized as
#' \eqn{\log(\sigma_v)} and \eqn{\mathrm{atanh}(\rho)} so that
#' \eqn{\sigma_v>0} and \eqn{|\rho|<1}. The spatial autoregressive parameter
#' \eqn{\lambda} is optimized directly subject to eigenvalue-based bounds.
#'
#' Analytic gradients are used for the likelihood optimization. If the Hessian
#' is requested, it is evaluated after optimization while keeping the final
#' probability ordering fixed.
#'
#' Standard errors can subsequently be obtained with \code{vcov()} or
#' \code{summary()}. The default \code{vce = "hessian"} uses the inverse
#' observed Hessian. For ME estimators, \code{vce = "sandwich"} provides an
#' operational model-based sandwich covariance matrix based on parametric
#' simulations of the joint model. The sandwich estimator is currently not
#' available for RIS.
#'
#' @return
#' An object of class \code{"binivml"}, containing the estimated coefficients
#' and the information required by the associated \code{coef}, \code{vcov},
#' \code{logLik}, \code{print}, and \code{summary} methods. The main elements
#' include:
#'
#' \item{coefficients}{Estimated parameters on the structural scale.}
#' \item{vcov_hessian}{Variance-covariance matrix obtained from the inverse
#' observed Hessian, when available.}
#' \item{se_hessian}{Hessian-based standard errors, when available.}
#' \item{call}{The matched function call.}
#' \item{callF}{The full matched call.}
#' \item{formula}{The model formula.}
#' \item{mf}{The model frame used in estimation.}
#' \item{data}{The original data supplied to the function.}
#' \item{y}{The binary dependent variable.}
#' \item{X}{The structural regressor matrix, including spatially lagged
#' regressors when requested.}
#' \item{Z}{The first-stage instrument matrix, formed from the exogenous
#' structural regressors and the excluded instruments.}
#' \item{excluded}{The matrix containing the excluded instruments.}
#' \item{xend}{The continuous endogenous regressor.}
#' \item{endog}{The name of the endogenous regressor.}
#' \item{listw}{The spatial weights matrix used in estimation.}
#' \item{method}{The probability evaluator used, either \code{"ME"} or
#' \code{"RIS"}.}
#' \item{varcov}{The covariance or precision representation used in the
#' probability recursion.}
#' \item{ordering}{The ordering rule used.}
#' \item{logLik}{The maximized joint log-likelihood.}
#' \item{opt}{A list containing optimization results, analytic scores,
#' ordering information, Hessian diagnostics, and timing information.}
#' \item{bounds}{The parameter bounds used by the optimizer.}
#'
#' @author Mauricio Sarrias and Gianfranco Piras
#' @examples
#' \donttest{
#' ## ---------------------------------------------------------
#' ## Data-generating process
#' ## ---------------------------------------------------------
#'
#' set.seed(12345)
#'
#' ## Spatial weights matrix from a regular lattice
#' nr <- 10
#' nc <- 10
#' n  <- nr * nc
#'
#' nb <- spdep::cell2nb(
#'   nrow = nr,
#'   ncol = nc,
#'   type = "queen"
#' )
#'
#' lw <- spdep::nb2listw(
#'   nb,
#'   style = "W",
#'   zero.policy = TRUE
#' )
#'
#' W <- spdep::listw2mat(lw)
#'
#' ## Exogenous regressors and excluded instruments
#' x1 <- stats::rnorm(n)
#' x3 <- stats::rnorm(n)
#' z1 <- stats::rnorm(n)
#' z2 <- stats::rnorm(n)
#'
#' ## Spatially lagged regressor
#' Wx1 <- as.numeric(W %*% x1)
#'
#' ## Parameters governing endogeneity
#' sigma_v <- 1
#' rho     <- 0.5
#'
#' zv   <- stats::rnorm(n)
#' zeta <- stats::rnorm(n)
#'
#' ## Reduced-form disturbance
#' v <- sigma_v * zv
#'
#' ## Continuous endogenous regressor
#' x2 <- 0.3 +
#'   0.5 * x1 -
#'   0.3 * x3 +
#'   0.8 * z1 -
#'   0.6 * z2 +
#'   v
#'
#' ## Structural disturbance correlated with v
#' eps <- rho * zv +
#'   sqrt(1 - rho^2) * zeta
#'
#' ## Structural parameters
#' lambda <- 0.6
#'
#' ## Latent spatial binary model with WX
#' rhs <- -0.2 +
#'   0.5 * x1 +
#'   0.8 * x2 -
#'   0.4 * x3 +
#'   0.35 * Wx1 +
#'   eps
#'
#' ystar <- solve(
#'   diag(n) - lambda * W,
#'   rhs
#' )
#'
#' y <- as.numeric(ystar > 0)
#'
#' dat <- data.frame(
#'   y  = y,
#'   x1 = x1,
#'   x2 = x2,
#'   x3 = x3,
#'   z1 = z1,
#'   z2 = z2
#' )
#'
#' ## Model with x2 endogenous, Wx1 in the structural equation,
#' ## and z1 and z2 as excluded instruments.
#' form <- y ~ x1 + x2 + x3 | x1 | z1 + z2
#'
#'
#' ## ---------------------------------------------------------
#' ## Mendell-Elston estimators
#' ## ---------------------------------------------------------
#'
#' ## ME using the covariance matrix and natural ordering
#' me_sigma_n <- sbinary_iv_ml(
#'   form,
#'   data = dat,
#'   listw = lw,
#'   endog = "x2",
#'   method = "ME",
#'   varcov = "sigma",
#'   ordering = "N"
#' )
#'
#' ## Hessian standard errors
#' summary(me_sigma_n)
#'
#' ## Sandwich standard errors
#' summary(
#'   me_sigma_n,
#'   vce = "sandwich",
#'   R = 50,
#'   seed = 123
#' )
#'
#'
#' ## ME using the covariance matrix and marginal ordering
#' me_sigma_m <- sbinary_iv_ml(
#'   form,
#'   data = dat,
#'   listw = lw,
#'   endog = "x2",
#'   method = "ME",
#'   varcov = "sigma",
#'   ordering = "M"
#' )
#'
#' summary(me_sigma_m)
#' summary(
#'   me_sigma_m,
#'   vce = "sandwich",
#'   R = 50,
#'   seed = 123
#' )
#'
#'
#' ## ME using the precision matrix and natural ordering
#' me_invsigma_n <- sbinary_iv_ml(
#'   form,
#'   data = dat,
#'   listw = lw,
#'   endog = "x2",
#'   method = "ME",
#'   varcov = "invsigma",
#'   ordering = "N"
#' )
#'
#' summary(me_invsigma_n)
#' summary(
#'   me_invsigma_n,
#'   vce = "sandwich",
#'   R = 50,
#'   seed = 123
#' )
#'
#'
#' ## ME using the precision matrix and marginal ordering
#' me_invsigma_m <- sbinary_iv_ml(
#'   form,
#'   data = dat,
#'   listw = lw,
#'   endog = "x2",
#'   method = "ME",
#'   varcov = "invsigma",
#'   ordering = "M"
#' )
#'
#' summary(me_invsigma_m)
#' summary(
#'   me_invsigma_m,
#'   vce = "sandwich",
#'   R = 50,
#'   seed = 123
#' )
#'
#'
#' ## ---------------------------------------------------------
#' ## RIS estimators
#' ## ---------------------------------------------------------
#'
#' ## RIS using the covariance matrix and marginal ordering
#' ris_sigma_m <- sbinary_iv_ml(
#'   form,
#'   data = dat,
#'   listw = lw,
#'   endog = "x2",
#'   method = "RIS",
#'   varcov = "sigma",
#'   ordering = "M",
#'   R = 100,
#'   seed = 123
#' )
#'
#' ## Hessian standard errors
#' summary(ris_sigma_m)
#'
#'
#' ## RIS using the precision matrix and marginal ordering
#' ris_invsigma_m <- sbinary_iv_ml(
#'   form,
#'   data = dat,
#'   listw = lw,
#'   endog = "x2",
#'   method = "RIS",
#'   varcov = "invsigma",
#'   ordering = "M",
#'   R = 100,
#'   seed = 123
#' )
#'
#' ## Hessian standard errors
#' summary(ris_invsigma_m)
#'
#'
#' ## ---------------------------------------------------------
#' ## SAR-probit submodel without WX regressors
#' ## ---------------------------------------------------------
#'
#' ## Use 0 in the second part of the formula when no WX
#' ## regressors enter the structural equation.
#' form_sar <- y ~ x1 + x2 + x3 | 0 | z1 + z2
#'
#' sar <- sbinary_iv_ml(
#'   form_sar,
#'   data = dat,
#'   listw = lw,
#'   endog = "x2",
#'   method = "ME",
#'   varcov = "invsigma",
#'   ordering = "M"
#' )
#'
#' summary(sar)
#' summary(
#'   sar,
#'   vce = "sandwich",
#'   R = 50,
#'   seed = 123
#' )
#' }
#' @references Sarrias, M. (2026). Mendell--Elston Approximate Likelihood for Spatial Probit Models with a Continuous Endogenous Regressor.
#' @seealso \code{\link[spldv]{sbinaryGMM}}, \code{\link[spldv]{sbinaryLGMM}}.
#' @keywords models
#' @rawNamespace import(Matrix,  except = c(cov2cor, toeplitz, update)) 
#' @import stats methods Formula
#' @importFrom sphet listw2dgCMatrix
#' @export
sbinary_iv_ml <- function(formula,
                       data,
                       subset,
                       na.action,
                       listw = NULL,
                       endog,
                       method = c("ME", "RIS"),
                       varcov = c("invsigma", "sigma"),
                       ordering = c("M", "N"),
                       R = 50L,
                       seed = 123L,
                       start = NULL,
                       lambda.margin = 1e-6,
                       maxit = 800L,
                       factr = 1e7,
                       pgtol = 1e-6,
                       hessian = TRUE,
                       print.init = FALSE,
                       verbose = TRUE,
                       ...) {

  method <- match.arg(method)
  varcov <- match.arg(varcov)
  ordering <- match.arg(ordering)

  if (missing(endog) || length(endog) != 1L || !is.character(endog) ||
      is.na(endog) || !nzchar(endog)) {
    stop("'endog' must be a single variable name.")
  }
  if (method == "RIS" && ordering != "M") {
    stop("RIS currently supports ordering = 'M' only.")
  }
  if (method == "RIS") {
    if (!is.numeric(R) || length(R) != 1L || !is.finite(R) || R < 1) {
      stop("'R' must be a positive integer.")
    }
    R <- as.integer(R)
    if (!is.numeric(seed) || length(seed) != 1L || !is.finite(seed)) {
      stop("'seed' must be a finite integer.")
    }
    seed <- as.integer(seed)
  }

  # --- Spatial weights matrix ---
  if (inherits(listw, "listw")) {
    W <- sphet::listw2dgCMatrix(listw)
  } else if (inherits(listw, "matrix")) {
    W <- Matrix::Matrix(listw, sparse = TRUE)
  } else if (inherits(listw, "Matrix")) {
    W <- listw
  } else {
    stop("Neighbourhood list or listw format unknown")
  }
  W <- Matrix::drop0(W)

  if (nrow(W) != ncol(W)) stop("W must be square.")

  # --- Model frame setup, following the existing spldv interface ---
  callT <- match.call(expand.dots = TRUE)
  callF <- match.call(expand.dots = FALSE)
  mf <- callT
  m <- match(c("formula", "data", "subset", "na.action"), names(mf), 0L)
  mf <- mf[c(1L, m)]
  f1 <- Formula::Formula(formula)

  if (length(f1)[2L] != 3L) {
    stop(
      "For sbinary_iv_ml(), formula must have three RHS parts: ",
      "y ~ x | wx | instruments. Use '| 0 |' when no WX terms are required."
    )
  }

  mf$formula <- f1
  mf[[1L]] <- as.name("model.frame")
  mf <- eval(mf, parent.frame())

  # --- Response ---
  y <- stats::model.response(mf)
  if (anyNA(y)) stop("NAs in dependent variable")
  if (!all(y %in% c(0, 1, TRUE, FALSE))) {
    stop("All dependent variables must be either 0, 1, TRUE or FALSE")
  }
  if (!is.numeric(y)) y <- as.numeric(y)
  y <- as.numeric(y)

  if (length(unique(y)) < 2L) {
    stop("The dependent variable must contain both outcome values 0 and 1.")
  }

  if (nrow(W) != length(y)) {
    stop("Number of spatial units in W is different to the number of observations.")
  }

  # --- Structural regressors: first RHS ---
  X0 <- stats::model.matrix(f1, data = mf, rhs = 1)
  contrastsX <- attr(X0, "contrasts")
  Xlevels <- .getXlevels(attr(mf, "terms"), mf)

  if (!endog %in% colnames(X0)) {
    stop(
      "The endogenous regressor '", endog,
      "' must enter the first RHS directly and must correspond to one column of model.matrix()."
    )
  }
  if (identical(endog, "(Intercept)")) {
    stop("The intercept cannot be specified as the endogenous regressor.")
  }

  endog_raw <- mf[[endog]]
  if (is.null(endog_raw) || !is.numeric(endog_raw)) {
    stop(
      "In this function, 'endog' must name a numeric variable in 'data' ",
      "that enters the first RHS directly."
    )
  }
  xend <- as.numeric(X0[, endog])

  if (any(!is.finite(xend))) {
    stop("The endogenous regressor contains non-finite values.")
  }
  if (stats::sd(xend) <= sqrt(.Machine$double.eps)) {
    stop("The endogenous regressor must have non-zero sample variation.")
  }

  # --- Spatially lagged regressors: second RHS ---
  x.for.w <- stats::model.matrix(f1, data = mf, rhs = 2)
  contrastsD <- attr(x.for.w, "contrasts")
  name.wx <- setdiff(colnames(x.for.w), "(Intercept)")

  if (endog %in% name.wx) {
    stop(
      "The endogenous regressor cannot also enter the WX part in this implementation."
    )
  }

  if (length(name.wx)) {
    if (!all(name.wx %in% colnames(X0))) {
      warning(
        "Some variables in WX do not appear in the first RHS. ",
        "Check the formula if this is not intended."
      )
    }
    WX <- W %*% x.for.w[, name.wx, drop = FALSE]
    WX <- as.matrix(WX)
    colnames(WX) <- paste0("lag_", name.wx)
    if (anyNA(WX)) stop("NAs in WX variables")
    X <- cbind(X0, WX)
  } else {
    X <- X0
  }

  if (anyNA(X)) stop("NAs in independent variables")
  if (nrow(X) != nrow(W)) {
    stop("Number of spatial units in W is different to the number of observations.")
  }

  # --- Excluded instruments: third RHS ---
  Zex0 <- stats::model.matrix(f1, data = mf, rhs = 3)
  contrastsI <- attr(Zex0, "contrasts")
  excluded.names <- setdiff(colnames(Zex0), "(Intercept)")

  if (!length(excluded.names)) {
    stop("At least one excluded instrument must be supplied in the third RHS.")
  }

  if (any(excluded.names %in% colnames(X))) {
    overlap <- intersect(excluded.names, colnames(X))
    stop(
      "The third RHS is reserved for excluded instruments. These variables ",
      "also appear in the structural equation: ", paste(overlap, collapse = ", ")
    )
  }

  Zexcluded <- Zex0[, excluded.names, drop = FALSE]
  Xexog <- X[, colnames(X) != endog, drop = FALSE]
  Z <- cbind(Xexog, Zexcluded)

  if (anyNA(Z)) stop("NAs in the first-stage instrument matrix.")
  if (anyDuplicated(colnames(Z))) {
    stop("Duplicated column names detected in the first-stage instrument matrix.")
  }

  qrz <- qr(as.matrix(Z))
  if (qrz$rank < ncol(Z)) {
    stop("The first-stage instrument matrix is rank deficient.")
  }
  if (nrow(Z) <= ncol(Z)) {
    stop("The first-stage instrument matrix has too many columns for the sample size.")
  }

  K <- ncol(X)
  L <- ncol(Z)

  # --- Problem constants and parameter bounds ---
  problem <- .sbivml_prepare_problem(W, lambda.margin = lambda.margin)
  bounds <- .sbivml_joint_bounds(problem, X = X, Z = Z)

  # --- Starting values ---
  if (is.null(start)) {
    start.internal <- .sbivml_make_start(
      y = y, X = X, xend = xend, Z = Z,
      bounds = bounds, problem = problem
    )
  } else {
    start.internal <- .sbivml_structural_start_to_internal(
      start = start, X = X, Z = Z, bounds = bounds
    )
  }

  if (print.init) {
    cat("\nStarting values (optimizer coordinates):\n")
    print(start.internal)
    cat("\nStarting values (structural scale):\n")
    print(.sbivml_structural_vector(start.internal, X = X, Z = Z))
  }

  # --- Common RIS draws ---
  draws <- if (method == "RIS") {
    .sbivml_make_ghk_draws(
      n = length(y), R = R, seed = seed, preserve_seed = TRUE
    )
  } else {
    NULL
  }

  engine <- if (method == "ME") {
    if (varcov == "invsigma") "ME_PM" else "ME_VC"
  } else {
    if (varcov == "invsigma") "RIS_PM" else "RIS_VC"
  }

  rule <- if (method == "RIS") {
    "M"
  } else if (ordering == "N") {
    "N"
  } else {
    "M"
  }

  if (verbose) {
    cat(
      "\n", method, " estimation of spatial binary probit with endogenous regressor\n",
      "Cholesky representation: ", varcov,
      " | ordering: ", ordering,
      if (method == "RIS") paste0(" | R: ", R) else "",
      "\n", sep = ""
    )
  }

  fit <- .sbivml_fit_joint(
    engine = engine,
    rule = rule,
    y = y,
    X = X,
    xend = xend,
    Z = Z,
    problem = problem,
    draws = draws,
    start = start.internal,
    maxit = as.integer(maxit),
    factr = factr,
    pgtol = pgtol,
    compute_hessian = isTRUE(hessian)
  )

  if (!isTRUE(fit$fit_ok)) {
    stop("sbinary_iv_ml optimization failed: ", fit$message)
  }

  if (verbose) {
    cat(
      "Convergence code: ", fit$convergence,
      " | log-likelihood: ", format(fit$logLik, digits = 8),
      "\n", sep = ""
    )
    if (!isTRUE(fit$optimizer_clean)) {
      cat("Warning: optimizer did not return convergence code 0.\n")
    }
    if (isTRUE(hessian) && !isTRUE(fit$vc_ok)) {
      cat("Warning: a valid positive-definite observed-information matrix was not obtained.\n")
    }
  }

  first.stage.start <- stats::lm.fit(
    x = as.matrix(Z),
    y = as.numeric(xend)
  )

  out <- structure(
    list(
      coefficients = fit$coef_structural,
      vcov_hessian = fit$vcov_structural,
      se_hessian = if (isTRUE(fit$vc_ok)) fit$se_structural else NULL,
      call = callT,
      callF = callF,
      formula = f1,
      mf = mf,
      data = data,
      y = y,
      X = X,
      X0 = X0,
      Z = Z,
      excluded = Zexcluded,
      xend = xend,
      endog = endog,
      listw = W,
      method = method,
      varcov = varcov,
      ordering = ordering,
      engine = engine,
      rule = rule,
      problem = problem,
      endog_col = match(endog, colnames(X)),
      R = if (method == "RIS") R else NULL,
      seed = if (method == "RIS") seed else NULL,
      logLik = fit$logLik,
      opt = fit,
      first.stage.start = first.stage.start,
      bounds = bounds,
      contrastsX = contrastsX,
      contrastsD = contrastsD,
      contrastsI = contrastsI,
      Xlevels = Xlevels
    ),
    class = "binivml"
  )

  out
}

## =========== -
## Helpers ----
## =========== -

.sbivml_perm_signature <- function(ord) {
  if (is.null(ord)) return(NA_character_)
  paste(as.integer(ord), collapse = ",")
}

.sbivml_valid_perm <- function(ord, n) {
  length(ord) == n && identical(sort(as.integer(ord)), seq_len(n))
}

.sbivml_safe_qnorm <- function(p) {
  stats::qnorm(pmin(pmax(p, .Machine$double.xmin), 1 - .Machine$double.eps))
}

.sbivml_mills_upper <- function(x) {
  lp <- stats::pnorm(x, log.p = TRUE)
  lf <- stats::dnorm(x, log = TRUE)
  out <- exp(lf - lp)
  ifelse(is.finite(out), out, pmax(abs(x), .Machine$double.eps))
}

.sbivml_one_sided_terms <- function(lower, upper) {
  ## Stable exact terms for the only interval types appearing in the
  ## binary-probit recursion.
  ##
  ## (-Inf,b):
  ##   log P = log Phi(b)
  ##   m      = E[Z | Z<b] = -phi(b)/Phi(b)
  ##
  ## (a,Inf):
  ##   log P = log(1-Phi(a))
  ##   m      = E[Z | Z>a] =  phi(a)/(1-Phi(a))
  ##
  ## score_coef multiplies the derivative of the finite bound in d log P.
  ## mean_deriv_coef multiplies it in d m.
  if (is.infinite(lower) && lower < 0 && is.finite(upper)) {
    b    <- upper
    logP <- stats::pnorm(b, log.p = TRUE)
    if (!is.finite(logP)) return(NULL)

    mills <- exp(stats::dnorm(b, log = TRUE) - logP)
    if (!is.finite(mills)) return(NULL)

    return(list(
      logp            = logP,
      mean            = -mills,
      score_coef      = mills,
      mean_deriv_coef = mills * (b + mills),
      finite_side     = "upper"
    ))
  }

  if (is.finite(lower) && is.infinite(upper) &&upper > 0) {
    a   <- lower
    logP <- stats::pnorm(a, lower.tail = FALSE, log.p = TRUE)
    if (!is.finite(logP)) return(NULL)

    mills <- exp(stats::dnorm(a, log = TRUE) - logP)
    if (!is.finite(mills)) return(NULL)

    return(list(
      logp            = logP,
      mean            = mills,
      score_coef      = -mills,
      mean_deriv_coef = mills * (mills - a),
      finite_side     = "lower"
    ))
  }

  stop(
    "Expected a one-sided interval; got lower=", lower,
    ", upper=", upper
  )
}

.sbivml_make_ghk_draws <- function(n, R = 500L, seed = 123L,
                              preserve_seed = TRUE) {
  ## Nested paired antithetic draws:
  ## u1, 1-u1, u2, 1-u2, ...
  ##
  ## Hence, for a common seed, the R=500 matrix is exactly the first
  ## 500 columns of the R=1000 matrix.
  if (R < 1L) stop("R must be positive.")

  old_exists <- exists(".Random.seed", envir = .GlobalEnv, inherits = FALSE)

  if (isTRUE(preserve_seed)) {
    old <- if (old_exists) {
      get(".Random.seed", envir = .GlobalEnv)
    } else {
      NULL
    }

    on.exit({
      if (old_exists) {
        assign(".Random.seed", old, envir = .GlobalEnv)
      } else if (exists(
        ".Random.seed",
        envir = .GlobalEnv,
        inherits = FALSE
      )) {
        rm(".Random.seed", envir = .GlobalEnv)
      }
    }, add = TRUE)
  }

  set.seed(seed)

  half <- ceiling(R / 2)
  U0   <- matrix(stats::runif(n * half), nrow = n, ncol = half)
  U    <- matrix(NA_real_, nrow = n, ncol = 2L * half)
  odd  <- seq.int(1L, 2L * half, by = 2L)
  U[, odd] <- U0
  U[, odd + 1L] <- 1 - U0
  U <- U[, seq_len(R), drop = FALSE]
  pmin(pmax(U, .Machine$double.xmin), 1 - .Machine$double.eps)
}

.sbivml_spatial_parameter_space <- function(W, endpoint_margin = 1e-6) {
  ## Eigenvalues are used to construct the admissible interval for lambda.
  ## For asymmetric W, eigenvalues may be complex. Consistently with
  ## our previous function in spldv, the bounds are based on their real parts.
  sym     <- isTRUE(all.equal(as.matrix(W), t(as.matrix(W)), check.attributes = FALSE))
  ev      <- eigen(as.matrix(W), only.values = TRUE, symmetric = sym)$values
  ev_real <- Re(ev)
  eig_min <- min(ev_real)
  eig_max <- max(ev_real)
  if (!(is.finite(eig_min) &&
        is.finite(eig_max) &&
        eig_min < 0 &&
        eig_max > 0)) {
    stop(
      "Could not construct the admissible interval for lambda from W."
    )
  }
  
  bound_lower <- 1 / eig_min
  bound_upper <- 1 / eig_max
  
  ## L-BFGS-B requires closed finite bounds. Optimize on a compact
  ## subset lying strictly inside the eigenvalue-based interval.
  lower <- bound_lower + endpoint_margin * max(1, abs(bound_lower))
  
  upper <- bound_upper - endpoint_margin * max(1, abs(bound_upper))
  
  if (!is.finite(lower) ||
      !is.finite(upper) ||
      lower >= upper) {
    stop(
      "Invalid eigenvalue-based spatial parameter interval."
    )
  }
  
  list(
    lower            = as.numeric(lower),
    upper            = as.numeric(upper),
    bound_lower      = as.numeric(bound_lower),
    bound_upper      = as.numeric(bound_upper),
    eig_min          = as.numeric(eig_min),
    eig_max          = as.numeric(eig_max),
    complex_spectrum = any(abs(Im(ev)) > 1e-8),
    endpoint_margin  = endpoint_margin
  )
}

.sbivml_projected_score <- function(par, score, lower, upper, tol = 1e-7) {
  ## Compute the projected score used to assess KKT stationarity under constraints.
  g        <- as.numeric(score)
  names(g) <- names(par)
  for (j in seq_along(par)) {
    at_lower <- is.finite(lower[j]) && par[j] <= lower[j] + tol * max(1, abs(lower[j]))
    at_upper <- is.finite(upper[j]) && par[j] >= upper[j] - tol * max(1, abs(upper[j]))

    ## KKT for maximization:
    ## lower boundary can be optimal when score <= 0;
    ## upper boundary can be optimal when score >= 0.
    if (at_lower && g[j] < 0) g[j] <- 0
    if (at_upper && g[j] > 0) g[j] <- 0
  }
  g
}

.sbivml_boundary_flags <- function(par, lower, upper, tol = 1e-6) {
  ## Flag parameters that lie at or sufficiently close to their optimization bounds.
  out        <- rep(FALSE, length(par))
  names(out) <- names(par)

  for (j in seq_along(par)) {
    lo <- is.finite(lower[j]) && par[j] <= lower[j] + tol * max(1, abs(lower[j]))
    hi <- is.finite(upper[j]) && par[j] >= upper[j] - tol * max(1, abs(upper[j]))
    out[j] <- lo || hi
  }
  out
}

.sbivml_factor_A <- function(A) {
  tryCatch(Matrix::lu(A), error = function(e) NULL)
}

.sbivml_solve_A <- function(A, RHS, factor = NULL) {
  ans <- NULL
  if (!is.null(factor)) {
    ans <- tryCatch(
      Matrix::solve(factor, RHS),
      error = function(e) NULL
    )
  }

  if (is.null(ans)) {
    ans <- tryCatch(
      Matrix::solve(A, RHS),
      error = function(e) NULL
    )
  }
  ans
}

.sbivml_exact_diag_omega <- function(base) {
  ## Compute diag(Omega) exactly as (1 - rho^2) * diag(A^{-1} A^{-T}) without forming Omega.
  B <- if (!is.null(base$B)) {
    base$B
  } else {
    I_n <- if (!is.null(base$pm_cache) && !is.null(base$pm_cache$I)) {
      base$pm_cache$I
    } else {
      Matrix::Diagonal(base$n)
    }
    B0 <- .sbivml_solve_A(base$A, I_n, factor = base$A_factor)
    if (is.null(B0)) NULL else tryCatch(as.matrix(B0), error = function(e) NULL)
  }

  if (is.null(B) || any(!is.finite(B))) return(NULL)
  
  out <- base$vf * rowSums(B * B)
  rm(B)

  if (any(!is.finite(out)) || any(out <= 0)) return(NULL)
  as.numeric(out)
}

.sbivml_chol_upper <- function(Prec, amd = FALSE, check_factor = FALSE) {
  ## Compute a sparse upper-Cholesky factor, optionally using AMD reordering, and return factorization diagnostics.
  S <- Matrix::forceSymmetric(Prec, uplo = "U")
  ch <- tryCatch(Matrix::Cholesky(S, perm = isTRUE(amd), LDL = FALSE, super = FALSE),
                 error = function(e) NULL)
  if (is.null(ch)) return(NULL)

  ex <- tryCatch(Matrix::expand2(ch, LDL = FALSE), error = function(e) NULL)
  if (is.null(ex) || is.null(ex[["L."]])) return(NULL)
  
  U <- Matrix::drop0(ex[["L."]])
  n <- nrow(S)
  perm0 <- tryCatch(as.integer(ch@perm),error = function(e) integer(0))
  perm <- if (length(perm0) == n) {
    perm0 + 1L
  } else {
    seq_len(n)
  }

  if (!.sbivml_valid_perm(perm, n)) {
    stop("Invalid permutation returned by sparse Cholesky.")
  }

  factor_error <- NA_real_

  if (isTRUE(check_factor)) {
    Sperm <- S[perm, perm, drop = FALSE]
    err <- Matrix::crossprod(U) - Sperm
    den <- max(1, as.numeric(Matrix::norm(Sperm, type = "I")))
    factor_error <- as.numeric(Matrix::norm(err, type = "I")) / den
  }

  list(
    U            = U,
    perm         = as.integer(perm),
    nnz_U        = Matrix::nnzero(U),
    factor_error = factor_error
  )
}

.sbivml_make_upper_row_cache <- function(M, require_positive_diag = TRUE) {
  ## Build a row-wise sparse cache of an upper-triangular matrix to avoid repeated row extraction in the ME/RIS recursions.
  n <- nrow(M)
  Ms <- if (inherits(M, "sparseMatrix")) {
    M
  } else {
    Matrix::Matrix(M, sparse = TRUE)
  }

  Ms    <- Matrix::drop0(Matrix::triu(Ms))
  diagv <- as.numeric(Matrix::diag(Ms))
  bad   <- length(diagv) != n || any(!is.finite(diagv))
  if (isTRUE(require_positive_diag)) bad <- bad || any(diagv <= 0)
  if (bad) stop("Invalid upper-triangular diagonal.")
  
  Mc <- methods::as(Ms, "CsparseMatrix")
  ii <- as.integer(Mc@i) + 1L
  jj <- rep.int(seq_len(n), diff(Mc@p))
  xx <- as.numeric(Mc@x)

  keep <- is.finite(xx) & xx != 0 & jj > ii
  ii   <- ii[keep]
  jj   <- jj[keep]
  xx   <- xx[keep]

  if (length(ii)) {
    grp <- split(seq_along(ii), factor(ii, levels = seq_len(n)), drop = FALSE)
    j_by_row <- lapply(grp,
      function(z) {
        if (length(z)) jj[z] else integer(0)
      }
    )

    x_by_row <- lapply(grp,
      function(z) {
        if (length(z)) xx[z] else numeric(0)
      }
    )
  } else {
    j_by_row <- replicate(n, integer(0), simplify = FALSE)
    x_by_row <- replicate(n, numeric(0), simplify = FALSE)
  }

  list(
    diag      = diagv,
    j         = j_by_row,
    x         = x_by_row,
    nnz_total = n + sum(lengths(j_by_row))
  )
}

.sbivml_chol_upper_derivative <- function(dPrec, U) {
  ## Compute dU from dPrec for Prec = U'U, as required by the analytic ME/RIS gradient.
  if (is.null(dPrec)) return(NULL)
  Ut <- Matrix::t(U)
  X <- tryCatch(Matrix::solve(Ut, dPrec), error = function(e) NULL)
  if (is.null(X)) return(NULL)
  
  Y <- tryCatch(Matrix::solve(Ut, Matrix::t(X)), error = function(e) NULL)
  if (is.null(Y)) return(NULL)
  
  M <- Matrix::t(Y)
  M <- 0.5 * (M + Matrix::t(M))
  F <- Matrix::triu(M)
  dM <- as.numeric(Matrix::diag(M))
  dF <- as.numeric(Matrix::diag(F))

  F <- F - Matrix::Diagonal(nrow(U), x = dF) + Matrix::Diagonal(nrow(U), x = 0.5 * dM)
  Matrix::drop0(F %*% U)
}

.sbivml_chol_upper_derivative_list <- function(dPrec_list, U, rho_index = NULL, rho = NULL) {
  ## Compute dU/dtheta for all parameters, using the closed-form derivative dU/drho_raw = rho * U when applicable.
  p <- length(dPrec_list)
  out <- vector("list", p)
  for (k in seq_len(p)) {
    if (!is.null(rho_index) && k == rho_index) {
      if (!is.null(rho) && is.finite(rho) && rho != 0) {
        out[[k]] <- Matrix::drop0(rho * U)
      }
    } else if (!is.null(dPrec_list[[k]])) {
      out[[k]] <- .sbivml_chol_upper_derivative(dPrec_list[[k]], U)
      if (is.null(out[[k]])) return(NULL)
    }
  }
  out
}

.sbivml_make_dU_caches <- function(dU_list, p) {
  ## Build row-wise sparse caches for the nonzero Cholesky-factor derivatives used in the ME/RIS gradient recursions.
  if (length(dU_list) != p) {
    stop(sprintf("Internal derivative-list length mismatch: length(dU_list)=%d, p=%d", length(dU_list), p))
  }
  caches <- vector("list", p)
  active <- integer(0)

  for (k in seq_len(p)) {
    if (!is.null(dU_list[[k]])) {
      caches[[k]] <- .sbivml_make_upper_row_cache(dU_list[[k]], require_positive_diag = FALSE)
      active <- c(active, k)
    }
  }
  list(
    caches = caches,
    active = active
  )
}

.sbivml_me_pm_grad_from_U <- function(lower, upper, dlower, dupper, U, dU_list) {
  ## Evaluate the precision-based Mendell-Elston recursion and its analytic gradient in a single backward pass.
  n <- length(lower)
  p <- ncol(dlower)

  Uc    <- .sbivml_make_upper_row_cache(U)
  dUc   <- .sbivml_make_dU_caches(dU_list, p)
  xhat  <- numeric(n)
  dxhat <- matrix(0, nrow = n, ncol = p)

  grad <- numeric(p)
  logp <- 0

  for (i in n:1) {
    Uii  <- Uc$diag[i]
    js   <- Uc$j[[i]]
    vals <- Uc$x[[i]]
    g    <- if (!length(js))  0  else  sum(vals * xhat[js])
    dg   <- numeric(p)
    if (length(js)) {
      dg <- as.numeric(crossprod(vals, dxhat[js, , drop = FALSE]))
    }

    dUii <- numeric(p)
    for (k in dUc$active) {
      dc      <- dUc$caches[[k]]
      dUii[k] <- dc$diag[i]
      djs     <- dc$j[[i]]
      if (length(djs)) {
        dg[k] <- dg[k] + sum(dc$x[[i]] * xhat[djs])
      }
    }

    if (is.finite(lower[i])) {
      lo <- Uii * lower[i] + g
      dlo <- Uii * dlower[i, ] + lower[i] * dUii + dg
    } else {
      lo <- -Inf
      dlo <- numeric(p)
    }

    if (is.finite(upper[i])) {
      up <- Uii * upper[i] + g
      dup <- Uii * dupper[i, ] + upper[i] * dUii + dg
    } else {
      up <- Inf
      dup <- numeric(p)
    }

    tt <- .sbivml_one_sided_terms(lo, up)

    if (is.null(tt)) {
      return(list(logp = -Inf, grad = rep(NA_real_, p)))
    }

    dbound <- if (identical(tt$finite_side, "upper")) dup else dlo
    
    grad       <- grad + tt$score_coef * dbound
    deta       <- tt$mean_deriv_coef * dbound
    x_i        <- (tt$mean - g) / Uii
    dx_i       <- (deta - dg - x_i * dUii) / Uii
    xhat[i]    <- x_i
    dxhat[i, ] <- dx_i
    logp <- logp + tt$logp
  }

  list(logp = as.numeric(logp), grad = as.numeric(grad))
}

.sbivml_chol_lower_derivative <- function(dSigma, L) {
  ## M = L^{-1} dSigma L^{-T}.  Compute it with triangular solves instead
  ## of explicitly forming L^{-1}; this is algebraically identical but
  ## avoids an inverse and two dense matrix multiplications.
  X <- tryCatch(forwardsolve(L, as.matrix(dSigma)), error = function(e) NULL)
  if (is.null(X)) return(NULL)

  Y <- tryCatch(forwardsolve(L, t(X)), error = function(e) NULL)
  if (is.null(Y)) return(NULL)

  M <- t(Y)
  M <- 0.5 * (M + t(M))
  F <- M
  F[upper.tri(F)] <- 0
  diag(F) <- 0.5 * diag(M)
  L %*% F
}

.sbivml_me_vc_grad <- function(lower, upper, Omega, dlower, dupper, dOmega_list, rho_index = NULL, rho = NULL) {
  ## Evaluate the covariance-based Mendell-Elston recursion and its analytic gradient in a single forward pass.
  n <- length(lower)
  p <- ncol(dlower)
  L <- tryCatch(t(chol(as.matrix(Omega))), error = function(e) NULL)
  if (is.null(L)) return(list(logp = -Inf, grad = rep(NA_real_, p)))
  
  dL <- vector("list", p)
  for (k in seq_len(p)) {
    if (!is.null(rho_index) && k == rho_index) {
      ## dOmega/d rho_raw = -2*rho*Omega => dL/d rho_raw = -rho*L.
      if (!is.null(rho) && is.finite(rho) && rho != 0) dL[[k]] <- -rho * L
    } else if (!is.null(dOmega_list[[k]])) {
      dL[[k]] <- .sbivml_chol_lower_derivative(dOmega_list[[k]], L)
      if (is.null(dL[[k]])) {
        return(list(logp = -Inf, grad = rep(NA_real_, p)))
      }
    }
  }

  active_dL <- which(!vapply(dL, is.null, logical(1)))
  eta       <- numeric(n)
  deta      <- matrix(0, nrow = n, ncol = p)
  grad      <- numeric(p)
  logp      <- 0
  for (i in seq_len(n)) {
    ind <- if (i > 1L) {
      seq_len(i - 1L)
    } else {
      integer(0)
    }

    g <- if (!length(ind)) {
      0
    } else {
      sum(L[i, ind] * eta[ind])
    }

    dg <- numeric(p)
    if (length(ind)) {
      dg <- as.numeric(crossprod(L[i, ind], deta[ind, , drop = FALSE]))
      for (k in active_dL) {
        dg[k] <- dg[k] + sum(dL[[k]][i, ind] * eta[ind])
      }
    }

    Lii  <- L[i, i]
    dLii <- numeric(p)
    for (k in active_dL) dLii[k] <- dL[[k]][i, i]
    lo_num <- lower[i] - g
    up_num <- upper[i] - g
    lo     <- lo_num / Lii
    up     <- up_num / Lii
    tt     <- .sbivml_one_sided_terms(lo, up)

    if (is.null(tt)) return(list(logp = -Inf, grad = rep(NA_real_, p)))
    if (is.finite(lower[i])) {
      dlo <- ((dlower[i, ] - dg) * Lii - lo_num * dLii) / Lii^2
    } else {
      dlo <- numeric(p)
    }

    if (is.finite(upper[i])) {
      dup <- ((dupper[i, ] - dg) * Lii - up_num * dLii) / Lii^2
    } else {
      dup <- numeric(p)
    }

    dbound    <- if (identical(tt$finite_side, "upper")) dup else dlo
    grad      <- grad + tt$score_coef * dbound
    eta[i]    <- tt$mean
    deta[i, ] <- tt$mean_deriv_coef * dbound
    logp      <- logp + tt$logp
  }

  list(logp = as.numeric(logp), grad = as.numeric(grad), L = L)
}

.sbivml_ris_pm_grad_from_U <- function(s, ds, U, dU_list, draws) {
  ## Evaluate the precision-based RIS/GHK simulator and its analytic gradient over all draws in a single backward recursion.
  n      <- length(s)
  R      <- ncol(draws)
  p      <- ncol(ds)
  Uc     <- .sbivml_make_upper_row_cache(U)
  dUc    <- .sbivml_make_dU_caches(dU_list, p)
  zdraw  <- matrix(0, nrow = n, ncol = R)
  dzdraw <- array(0, dim = c(n, R, p))
  logp_r <- rep(0, R)
  grad_r <- matrix(0, nrow = R, ncol = p)

  alive    <- rep(TRUE, R)
  log_xmin <- log(.Machine$double.xmin)
  for (i in n:1) {
    rr <- which(alive)
    if (!length(rr)) break
    Uii  <- Uc$diag[i]
    js   <- Uc$j[[i]]
    vals <- Uc$x[[i]]
    g <- if (!length(js)) {
      rep(0, length(rr))
    } else {
      zsub <- matrix(zdraw[js, rr, drop = FALSE], nrow = length(js), ncol = length(rr))
      as.numeric(crossprod(vals, zsub))
    }
    nu <- as.numeric(Uii * s[i] + g)
    lp <- stats::pnorm(nu, log.p = TRUE)
    bad <- !is.finite(lp)
    if (any(bad)) alive[rr[bad]] <- FALSE
    ok <- which(!bad)
    if (!length(ok)) next

    .sbivml_ok <- rr[ok]
    nu_ok <- nu[ok]
    lp_ok <- lp[ok]

    dg <- matrix(0, nrow = length(.sbivml_ok), ncol = p)
    if (length(js)) {
      zsub <- matrix(zdraw[js, .sbivml_ok, drop = FALSE], nrow = length(js), ncol = length(.sbivml_ok))
      for (k in seq_len(p)) {
        dzsub <- matrix(dzdraw[js, .sbivml_ok, k], nrow = length(js), ncol = length(.sbivml_ok))
        dg[, k] <- as.numeric(crossprod(vals, dzsub))
        if (k %in% dUc$active) {
          dc <- dUc$caches[[k]]
          djs <- dc$j[[i]]

          if (length(djs)) {
            zsub_d <- matrix(zdraw[djs, .sbivml_ok, drop = FALSE], nrow = length(djs), ncol = length(.sbivml_ok))
            dg[, k] <- dg[, k] + as.numeric(crossprod(dc$x[[i]], zsub_d))
          }
        }
      }
    }

    dUii <- numeric(p)
    for (k in dUc$active) dUii[k] <- dUc$caches[[k]]$diag[i]

    dnu <- matrix(0, nrow = length(.sbivml_ok), ncol = p)
    for (k in seq_len(p)) dnu[, k] <- Uii * ds[i, k] + s[i] * dUii[k] + dg[, k]
    

    ratio <- .sbivml_mills_upper(nu_ok)
    grad_r[.sbivml_ok, ] <- grad_r[.sbivml_ok, , drop = FALSE] + ratio * dnu
    logp_r[.sbivml_ok] <- logp_r[.sbivml_ok] + lp_ok
    pcond <- exp(pmax(lp_ok, log_xmin))
    pcond <- pmin(pcond, 1 - .Machine$double.eps)
    eta <- .sbivml_safe_qnorm(draws[i, .sbivml_ok] * pcond)
    active_draw <- lp_ok > log_xmin & pcond < 1 - .Machine$double.eps

    mult <- rep(0, length(.sbivml_ok))

    if (any(active_draw)) {
      phi_nu <- stats::dnorm(nu_ok[active_draw])
      phi_eta <- stats::dnorm(eta[active_draw])
      mult[active_draw] <- draws[i, .sbivml_ok[active_draw]] * phi_nu / pmax(phi_eta, .Machine$double.xmin)
    }

    deta <- dnu * mult
    z_i <-(eta - g[ok]) / Uii
    dz_i <- matrix(0, nrow = length(.sbivml_ok), ncol = p)
    for (k in seq_len(p)) dz_i[, k] <- (deta[, k] - dg[, k] - z_i * dUii[k]) / Uii
    zdraw[i, .sbivml_ok] <- z_i
    for (k in seq_len(p)) dzdraw[i, .sbivml_ok, k] <- dz_i[, k]
  }

  if (any(!alive)) {
    logp_r[!alive] <- -Inf
    grad_r[!alive, ] <- 0
  }

  m <- max(logp_r)
  if (!is.finite(m)) return(list(logp = -Inf, grad = rep(NA_real_, p)))
  w <- exp(logp_r - m)
  w[!is.finite(w)] <- 0
  bad_rows <- !is.finite(logp_r) | !stats::complete.cases(grad_r)
  if (any(bad_rows)) {
    w[bad_rows] <- 0
    grad_r[bad_rows, ] <- 0
  }

  sw <- sum(w)
  if (!is.finite(sw) ||sw <= 0) return(list(logp = -Inf, grad = rep(NA_real_, p)))
  
  list(
    logp = as.numeric(m + log(mean(w))),
    grad = as.numeric(crossprod(w / sw, grad_r))
  )
}

.sbivml_ris_vc_grad <- function(s, ds, Omega, dOmega_list, draws, rho_index = NULL, rho = NULL) {
  ## Evaluate the covariance-based RIS likelihood approximation and its analytic gradient using the GHK recursion.
  n <- length(s)
  R <- ncol(draws)
  p <- ncol(ds)
  L <- tryCatch(t(chol(as.matrix(Omega))), error = function(e) NULL)
  if (is.null(L)) return(list(logp = -Inf, grad = rep(NA_real_, p)))
  
  dL <- vector("list", p)
  for (k in seq_len(p)) {
    if (!is.null(rho_index) && k == rho_index) {
      ## dOmega/d rho_raw = -2*rho*Omega, hence dL/d rho_raw = -rho*L.
      ## Keep this closed-form scale derivative, but use the legacy
      ## parameter-loop recursion below to avoid large 3D block copies in R.
      if (!is.null(rho) && is.finite(rho) && rho != 0) {
        dL[[k]] <- -rho * L
      }
    } else if (!is.null(dOmega_list[[k]])) {
      dL[[k]] <- .sbivml_chol_lower_derivative(dOmega_list[[k]], L)
      if (is.null(dL[[k]])) return(list(logp = -Inf, grad = rep(NA_real_, p)))
    }
  }

  eta      <- matrix(0, nrow = n, ncol = R)
  deta     <- array(0, dim = c(n, R, p))
  logp_r   <- rep(0, R)
  grad_r   <- matrix(0, nrow = R, ncol = p)
  alive    <- rep(TRUE, R)
  log_xmin <- log(.Machine$double.xmin)

  for (i in seq_len(n)) {
    rr <- which(alive)
    if (!length(rr)) break

    ind <- if (i > 1L) seq_len(i - 1L) else integer(0)
    if (!length(ind)) {
      g <- rep(0, length(rr))
    } else {
      eta_sub <- matrix(eta[ind, rr, drop = FALSE], nrow = length(ind), ncol = length(rr))
      g <- as.numeric(crossprod(L[i, ind], eta_sub))
    }

    Lii   <- L[i, i]
    delta <- s[i] - g
    nu    <- delta / Lii
    lp    <- stats::pnorm(nu, log.p = TRUE)
    bad   <- !is.finite(lp)
    if (any(bad)) alive[rr[bad]] <- FALSE
    ok <- which(!bad)
    if (!length(ok)) next

    .sbivml_ok <- rr[ok]
    nu_ok     <- nu[ok]
    delta_ok  <- delta[ok]
    lp_ok     <- lp[ok]

    dg <- matrix(0, nrow = length(.sbivml_ok), ncol = p)

    if (length(ind)) {
      eta_sub <- matrix(
        eta[ind, .sbivml_ok, drop = FALSE],
        nrow = length(ind),
        ncol = length(.sbivml_ok)
      )

      for (k in seq_len(p)) {
        deta_sub <- matrix(
          deta[ind, .sbivml_ok, k],
          nrow = length(ind),
          ncol = length(.sbivml_ok)
        )
        dg[, k] <- as.numeric(crossprod(L[i, ind], deta_sub))
        if (!is.null(dL[[k]])) {
          dg[, k] <- dg[, k] + as.numeric(crossprod(dL[[k]][i, ind], eta_sub))
        }
      }
    }

    dLii <- numeric(p)

    for (k in seq_len(p)) {
      if (!is.null(dL[[k]])) {
        dLii[k] <- dL[[k]][i, i]
      }
    }

    dnu <- matrix(0, nrow = length(.sbivml_ok), ncol = p)
    for (k in seq_len(p)) dnu[, k] <-((ds[i, k] - dg[, k]) * Lii - delta_ok * dLii[k]) / Lii^2
    
    ratio               <- .sbivml_mills_upper(nu_ok)
    grad_r[.sbivml_ok, ] <- grad_r[.sbivml_ok, , drop = FALSE] + ratio * dnu
    logp_r[.sbivml_ok]   <- logp_r[.sbivml_ok] + lp_ok
    pcond               <- exp(pmax(lp_ok, log_xmin))
    pcond               <- pmin(pcond, 1 - .Machine$double.eps)
    eta_i               <- .sbivml_safe_qnorm(draws[i, .sbivml_ok] * pcond)
    eta[i, .sbivml_ok]   <- eta_i
    active_draw         <- lp_ok > log_xmin & pcond < 1 - .Machine$double.eps
    mult                <- rep(0, length(.sbivml_ok))

    if (any(active_draw)) {
      phi_nu <- stats::dnorm(nu_ok[active_draw])
      phi_eta <- stats::dnorm(eta_i[active_draw])
      mult[active_draw] <-draws[i, .sbivml_ok[active_draw]] * phi_nu / pmax(phi_eta, .Machine$double.xmin)
    }

    for (k in seq_len(p)) deta[i, .sbivml_ok, k] <- mult * dnu[, k]
  }

  if (any(!alive)) {
    logp_r[!alive] <- -Inf
    grad_r[!alive, ] <- 0
  }

  m <- max(logp_r)
  if (!is.finite(m)) return(list(logp = -Inf, grad = rep(NA_real_, p)))
  w <- exp(logp_r - m)
  w[!is.finite(w)] <- 0

  bad_rows <- !is.finite(logp_r) | !stats::complete.cases(grad_r)

  if (any(bad_rows)) {
    w[bad_rows] <- 0
    grad_r[bad_rows, ] <- 0
  }

  sw <- sum(w)
  if (!is.finite(sw) || sw <= 0) return(list(logp = -Inf, grad = rep(NA_real_, p)))
  
  list(
    logp = as.numeric(m + log(mean(w))),
    grad = as.numeric(crossprod(w / sw, grad_r))
  )
}

.sbivml_mg_me_order <- function(lower, upper, diagOmega, precision_storage = TRUE) {
  ## Construct the Mendell-Elston ordering from marginal truncation probabilities, reversing it for backward precision recursions.
  sd_i <- sqrt(diagOmega)
  p_i <- stats::pnorm(upper / sd_i) - stats::pnorm(lower / sd_i)
  if (any(!is.finite(p_i))) return(NULL)
  
  ## Covariance recursion is forward: smallest p first.
  ord_forward <- order(p_i, decreasing = FALSE)

  if (isTRUE(precision_storage)) {
    ## Precision recursion processes n:1, so store the reverse.
    return(as.integer(rev(ord_forward)))
  }

  as.integer(ord_forward)
}

.sbivml_mg_ris_order <- function(s, diagOmega, precision_storage = TRUE) {
  ## Construct the RIS ordering from marginal sign probabilities, reversing it for backward precision recursions.
  p_i <- stats::pnorm(s / sqrt(diagOmega))
  if (any(!is.finite(p_i))) return(NULL)
  
  ord_forward <- order(p_i,decreasing = FALSE)
  if (isTRUE(precision_storage)) {
    return(as.integer(rev(ord_forward)))
  }
  as.integer(ord_forward)
}

.sbivml_sign_adjust <- function(M, q) {
  ## Apply the binary-sign transformation Q M Q, with Q = diag(2y - 1), to orient all truncation constraints consistently.
  if (inherits(M, "Matrix")) {
    Q <- Matrix::Diagonal(x = as.numeric(q))
    Matrix::drop0(Q %*% M %*% Q)
  } else {
    M * tcrossprod(q, q)
  }
}

.sbivml_pm_factor <- function(Prec, ord_stat, append_amd = FALSE, check_factor = FALSE) {
  ## Factor the precision matrix after statistical ordering, optionally appending AMD to reduce sparse Cholesky fill-in.
  n <- nrow(Prec)
  if (!.sbivml_valid_perm(ord_stat, n)) return(NULL)

  Pstat <- Prec[ord_stat, ord_stat, drop = FALSE]
  ff    <- .sbivml_chol_upper(Pstat, amd = isTRUE(append_amd), check_factor = check_factor)
  if (is.null(ff)) return(NULL)

  rel <- if (isTRUE(append_amd)) ff$perm else seq_len(n)
  if (!.sbivml_valid_perm(rel, n)) return(NULL)

  ord_final <- as.integer(ord_stat[rel])
  if (!.sbivml_valid_perm(ord_final, n)) return(NULL)

  list(
    U = ff$U,
    ord_stat = as.integer(ord_stat),
    ord_fill_relative = as.integer(rel),
    ord_final = ord_final,
    amd_nontrivial = isTRUE(append_amd) && any(rel != seq_len(n)),
    nnz_U = ff$nnz_U,
    factor_error = ff$factor_error,
    nnz_P_upper = Matrix::nnzero(Matrix::triu(Pstat[rel, rel, drop = FALSE]))
  )
}


## =========================== -
## Internal parameter handling ----
## ============================ -

.sbivml_parameter_names <- function(X, Z) {
  c(colnames(X), "lambda", paste0("pi_", colnames(Z)), "log_sigma_v", "rho_raw")
}

.sbivml_structural_names <- function(X, Z) {
  c(colnames(X), "lambda", paste0("pi_", colnames(Z)), "sigma_v", "rho")
}

.sbivml_parameter_index <- function(X, Z) {
  K           <- ncol(X)
  L           <- ncol(Z)
  idx_beta    <- seq_len(K)
  idx_lambda  <- K + 1L
  idx_pi      <- idx_lambda + seq_len(L)
  idx_lsigma  <- idx_lambda + L + 1L
  idx_rho_raw <- idx_lsigma + 1L

  list(
    beta        = idx_beta,
    lambda      = idx_lambda,
    pi          = idx_pi,
    log_sigma_v = idx_lsigma,
    rho_raw     = idx_rho_raw,
    p           = idx_rho_raw
  )
}

.sbivml_make_parameter_vector <- function(beta, lambda, pi, sigma_v, rho, X, Z) {
  if (length(beta) != ncol(X)) stop("Incorrect beta dimension.")
  if (length(pi) != ncol(Z)) stop("Incorrect pi dimension.")
  if (!is.finite(sigma_v) || sigma_v <= 0) {
    stop("sigma_v must be strictly positive.")
  }
  if (!is.finite(rho) || abs(rho) >= 1) {
    stop("rho must lie strictly inside (-1,1).")
  }

  out <- c(
    as.numeric(beta),
    as.numeric(lambda),
    as.numeric(pi),
    log(as.numeric(sigma_v)),
    atanh(as.numeric(rho))
  )
  names(out) <- .sbivml_parameter_names(X, Z)
  out
}

.sbivml_read_parameters <- function(par, X, Z) {
  ii <- .sbivml_parameter_index(X, Z)
  beta <- as.numeric(par[ii$beta])
  names(beta) <- colnames(X)

  pi_hat <- as.numeric(par[ii$pi])
  names(pi_hat) <- colnames(Z)

  log_sigma_v <- as.numeric(par[ii$log_sigma_v])
  rho_raw <- as.numeric(par[ii$rho_raw])

  list(
    beta = beta,
    lambda = as.numeric(par[ii$lambda]),
    pi = pi_hat,
    log_sigma_v = log_sigma_v,
    rho_raw = rho_raw,
    sigma_v = exp(log_sigma_v),
    rho = tanh(rho_raw),
    index = ii
  )
}

.sbivml_structural_vector <- function(par, X, Z) {
  pp <- .sbivml_read_parameters(par, X, Z)
  out <- c(
    unname(pp$beta),
    unname(pp$lambda),
    unname(pp$pi),
    unname(pp$sigma_v),
    unname(pp$rho)
  )
  names(out) <- .sbivml_structural_names(X, Z)
  out
}

.sbivml_structural_jacobian <- function(par, X, Z) {
  pp <- .sbivml_read_parameters(par, X, Z)
  p <- length(par)
  J <- diag(p)
  rownames(J) <- .sbivml_structural_names(X, Z)
  colnames(J) <- names(par)
  J[p - 1L, p - 1L] <- pp$sigma_v
  J[p, p] <- 1 - pp$rho^2
  J
}

.sbivml_joint_bounds <- function(problem, X, Z) {
  ii <- .sbivml_parameter_index(X, Z)
  p <- ii$p

  lower <- rep(-Inf, p)
  upper <- rep(Inf, p)
  lower[ii$lambda] <- problem$lambda_space$lower
  upper[ii$lambda] <- problem$lambda_space$upper

  names(lower) <- .sbivml_parameter_names(X, Z)
  names(upper) <- names(lower)

  list(
    lower = lower,
    upper = upper,
    spatial = problem$lambda_space
  )
}

.sbivml_clip_lambda_start <- function(out, bounds) {
  jlam <- which(names(out) == "lambda")
  if (length(jlam) != 1L) stop("Could not locate lambda in starting values.")
  lo <- bounds$lower[jlam]
  hi <- bounds$upper[jlam]
  width <- hi - lo
  eps <- max(1e-8, 1e-6 * abs(width))
  out[jlam] <- min(max(out[jlam], lo + eps), hi - eps)
  out
}

.sbivml_make_start <- function(y, X, xend, Z, bounds, problem) {
  fs <- stats::lm.fit(x = as.matrix(Z), y = as.numeric(xend))
  pi_hat <- as.numeric(fs$coefficients)
  pi_hat[!is.finite(pi_hat)] <- 0

  vhat <- as.numeric(xend - Z %*% pi_hat)
  sigma_hat <- sqrt(mean(vhat^2))
  if (!is.finite(sigma_hat) || sigma_hat <= 0) sigma_hat <- 1

  beta_start <- rep(0, ncol(X))
  fit0 <- try(
    stats::glm.fit(x = as.matrix(X), y = as.numeric(y), family = stats::binomial(link = "probit")),
    silent = TRUE
  )
  if (!inherits(fit0, "try-error") &&
      length(fit0$coefficients) == ncol(X)) {
    bb <- as.numeric(fit0$coefficients)
    bb[!is.finite(bb)] <- 0
    beta_start <- bb
  }

  lambda_start <- 0
  Wy <- as.numeric(problem$W %*% as.numeric(y))
  sy <- stats::sd(as.numeric(y))
  swy <- stats::sd(Wy)
  if (is.finite(sy) && is.finite(swy) && sy > 0 && swy > 0) {
    cc <- suppressWarnings(stats::cor(as.numeric(y), Wy))
    if (is.finite(cc)) lambda_start <- as.numeric(cc)
  }

  out <- .sbivml_make_parameter_vector(
    beta = beta_start,
    lambda = lambda_start,
    pi = pi_hat,
    sigma_v = sigma_hat,
    rho = 0,
    X = X,
    Z = Z
  )

  .sbivml_clip_lambda_start(out, bounds)
}

.sbivml_structural_start_to_internal <- function(start, X, Z, bounds) {
  p <- length(.sbivml_structural_names(X, Z))
  if (length(start) != p) {
    stop(
      "Incorrect number of starting values. Expected ", p,
      " values ordered as beta, lambda, pi, sigma_v, rho."
    )
  }

  K <- ncol(X)
  L <- ncol(Z)
  beta <- start[seq_len(K)]
  lambda <- start[K + 1L]
  pi <- start[(K + 2L):(K + 1L + L)]
  sigma_v <- start[K + L + 2L]
  rho <- start[K + L + 3L]

  out <- .sbivml_make_parameter_vector(
    beta = beta, lambda = lambda, pi = pi,
    sigma_v = sigma_v, rho = rho, X = X, Z = Z
  )
  .sbivml_clip_lambda_start(out, bounds)
}

## =================== -
## Problem preparation ----
## =================== -

.sbivml_prepare_problem <- function(W, lambda.margin = 1e-6) {
  if (nrow(W) != ncol(W)) stop("W must be square.")
  sp  <- .sbivml_spatial_parameter_space(W,endpoint_margin = lambda.margin)
  n   <- nrow(W)
  I_n <- Matrix::Diagonal(n)

  list( 
    W = W,
    n = n,
    pm_cache      = list(I = I_n, Wplus = Matrix::drop0(W + Matrix::t(W)), WtW = Matrix::drop0(Matrix::crossprod(W))),
    lambda_margin = lambda.margin,
    lambda_space  = sp
  )
}

## ============================== -
## Joint likelihood common objects ----
## ============================== -

.sbivml_joint_base <- function(par, y, X, xend, Z, W,
                              need_pm = TRUE,
                              need_vc = FALSE,
                              pm_cache = NULL) {
  n    <- length(y)
  K    <- ncol(X)
  L    <- ncol(Z)
  npar <- length(par)

  pp <- .sbivml_read_parameters(par, X, Z)
  ii <- pp$index

  if (!is.finite(pp$sigma_v) || pp$sigma_v <= 0 || !is.finite(pp$rho) || abs(pp$rho) >= 1) {
    return(NULL)
  }
  v      <- as.numeric(xend - Z %*% pp$pi)
  sigma2 <- pp$sigma_v^2

  log_fx <- -0.5 * n * log(2 * pi) - n * log(pp$sigma_v) - 0.5 * sum(v^2) / sigma2
  c_rho_sigma <- pp$rho / pp$sigma_v
  rhs <- as.numeric(X %*% pp$beta + c_rho_sigma * v)

  I_n <- if (!is.null(pm_cache) && !is.null(pm_cache$I)) pm_cache$I else Matrix::Diagonal(n)
  A        <- Matrix::drop0(I_n - pp$lambda * W)
  A_factor <- .sbivml_factor_A(A)

  RHS  <- cbind(rhs, X, Z, v)
  SOL0 <- .sbivml_solve_A(A, RHS, factor = A_factor)
  SOL  <- if (is.null(SOL0)) NULL else tryCatch(as.matrix(SOL0), error = function(e) NULL)

  if (is.null(SOL) || any(!is.finite(SOL))) return(NULL)

  mu   <- as.numeric(SOL[, 1L])
  ix_X0 <- 2L
  ix_X1 <- ix_X0 + K - 1L
  B_X   <- SOL[, ix_X0:ix_X1, drop = FALSE]

  ix_Z0 <- ix_X1 + 1L
  ix_Z1 <- ix_Z0 + L - 1L
  B_Z   <- SOL[, ix_Z0:ix_Z1, drop = FALSE]
  B_v   <- as.numeric(SOL[, ix_Z1 + 1L])
  B_W_mu0 <- .sbivml_solve_A(A, W %*% mu, factor = A_factor)
  B_W_mu <- if (is.null(B_W_mu0)) NULL else
    tryCatch(as.numeric(B_W_mu0), error = function(e) NULL)

  if (is.null(B_W_mu) || any(!is.finite(B_W_mu))) return(NULL)

  dmu <- matrix(0, nrow = n, ncol = npar)
  dmu[, ii$beta] <- B_X
  dmu[, ii$lambda] <- B_W_mu
  dmu[, ii$pi] <- -c_rho_sigma * B_Z
  dmu[, ii$log_sigma_v] <- -c_rho_sigma * B_v
  dmu[, ii$rho_raw] <- ((1 - pp$rho^2) / pp$sigma_v) * B_v

  vf <- 1 - pp$rho^2
  if (!is.finite(vf) || vf <= 1e-10) return(NULL)

  g_fx <- numeric(npar)
  g_fx[ii$pi] <- as.numeric(crossprod(Z, v)) / sigma2
  g_fx[ii$log_sigma_v] <- -n + sum(v^2) / sigma2

  out <- list(
    n = n,
    npar = npar,
    K = K,
    L = L,
    pp = pp,
    idx_beta = ii$beta,
    idx_lambda = ii$lambda,
    idx_pi = ii$pi,
    idx_lsigma = ii$log_sigma_v,
    idx_rho_raw = ii$rho_raw,
    v = v,
    log_fx = log_fx,
    g_fx = g_fx,
    X = X,
    A = A,
    A_factor = A_factor,
    pm_cache = pm_cache,
    mu = mu,
    dmu = dmu,
    vf = vf
  )

  if (isTRUE(need_pm)) {
    if (!is.null(pm_cache) &&
        !is.null(pm_cache$Wplus) &&
        !is.null(pm_cache$WtW) &&
        !is.null(pm_cache$I)) {
      S <- Matrix::drop0(
        pm_cache$I -
          pp$lambda * pm_cache$Wplus +
          pp$lambda^2 * pm_cache$WtW
      )
      dS_lambda <- Matrix::drop0(
        -pm_cache$Wplus +
          2 * pp$lambda * pm_cache$WtW
      )
    } else {
      S <- Matrix::crossprod(A)
      dS_lambda <- -(
        Matrix::crossprod(W, A) +
          Matrix::crossprod(A, W)
      )
    }

    Prec <- Matrix::drop0(S / vf)
    dPrec <- vector("list", npar)
    dPrec[[ii$lambda]] <- Matrix::drop0(dS_lambda / vf)

    out$Prec <- Prec
    out$dPrec_list <- dPrec
  }

  if (isTRUE(need_vc)) {
    B0 <- .sbivml_solve_A(
      A,
      if (!is.null(pm_cache) && !is.null(pm_cache$I)) {
        pm_cache$I
      } else {
        Matrix::Diagonal(n)
      },
      factor = A_factor
    )
    B <- if (is.null(B0)) NULL else tryCatch(as.matrix(B0), error = function(e) NULL)

    if (is.null(B) || any(!is.finite(B))) return(NULL)

    Omega <- vf * tcrossprod(B)
    dOmega <- vector("list", npar)

    X0 <- .sbivml_solve_A(
      A,
      W %*% Omega,
      factor = A_factor
    )
    Xlambda <- if (is.null(X0)) NULL else
      tryCatch(as.matrix(X0), error = function(e) NULL)

    if (is.null(Xlambda) || any(!is.finite(Xlambda))) return(NULL)

    dOmega[[ii$lambda]] <- Xlambda + t(Xlambda)

    out$B <- B
    out$Omega <- Omega
    out$dOmega_list <- dOmega
  }

  out
}

## ====================== -
## ME and RIS evaluators ----
## ====================== -

.sbivml_build_me_pm_objects <- function(par, y, X, xend, Z, problem) {
  base <- .sbivml_joint_base(
    par,
    y        = y,
    X        = X,
    xend     = xend,
    Z        = Z,
    W        = problem$W,
    need_pm  = TRUE,
    need_vc  = FALSE,
    pm_cache = problem$pm_cache
  )

  if (is.null(base)) return(NULL)

  lower <- ifelse(y == 1, -Inf, base$mu)
  upper <- ifelse(y == 1, base$mu, Inf)

  dlower <- matrix(0, nrow = base$n, ncol = base$npar)
  dupper <- matrix(0, nrow = base$n, ncol = base$npar)
  dlower[y == 0, ] <- base$dmu[y == 0, , drop = FALSE]
  dupper[y == 1, ] <- base$dmu[y == 1, , drop = FALSE]

  list(
    base       = base,
    lower      = lower,
    upper      = upper,
    dlower     = dlower,
    dupper     = dupper,
    Prec       = base$Prec,
    dPrec_list = base$dPrec_list
  )
}

.sbivml_build_me_vc_objects <- function(par, y, X, xend, Z, problem) {
  base <- .sbivml_joint_base(
    par,
    y        = y,
    X        = X,
    xend     = xend,
    Z        = Z,
    W        = problem$W,
    need_pm  = FALSE,
    need_vc  = TRUE,
    pm_cache = problem$pm_cache
  )
  if (is.null(base)) return(NULL)

  lower  <- ifelse(y == 1, -Inf, base$mu)
  upper  <- ifelse(y == 1, base$mu, Inf)
  dlower <- matrix(0, nrow = base$n, ncol = base$npar)
  dupper <- matrix(0, nrow = base$n, ncol = base$npar)
  dlower[y == 0, ] <- base$dmu[y == 0, , drop = FALSE]
  dupper[y == 1, ] <- base$dmu[y == 1, , drop = FALSE]

  list(
    base   = base,
    lower  = lower,
    upper  = upper,
    dlower = dlower,
    dupper = dupper
  )
}

.sbivml_eval_me_pm <- function(par, y, X, xend, Z, problem,
                              rule = c("N", "M"),
                              fixed_order = NULL,
                              check_factor = FALSE) {
  rule <- match.arg(rule)
  pm   <- .sbivml_build_me_pm_objects(par, y, X, xend, Z, problem)

  fail <- function(order = NULL) {
    list(
      logLik            = -Inf,
      gradient          = rep(NA_real_, length(par)),
      order             = order,
      ord_stat          = NULL,
      ord_fill_relative = NULL,
      rule              = rule,
      engine            = "ME_PM",
      amd_applied       = identical(rule, "M") && is.null(fixed_order),
      amd_nontrivial    = NA
    )
  }

  if (is.null(pm)) return(fail())
  n <- pm$base$n

  if (!is.null(fixed_order)) {
    if (!.sbivml_valid_perm(fixed_order, n)) return(fail())
    ord_stat   <- as.integer(fixed_order)
    append_amd <- FALSE
  } else if (rule == "N") {
    ord_stat   <- seq_len(n)
    append_amd <- FALSE
  } else {
    diagOmega <- .sbivml_exact_diag_omega(pm$base)
    if (is.null(diagOmega)) return(fail())

    ord_stat <- .sbivml_mg_me_order(
      pm$lower,
      pm$upper,
      diagOmega,
      precision_storage = TRUE
    )
    append_amd <- TRUE
  }

  if (is.null(ord_stat) || !.sbivml_valid_perm(ord_stat, n)) return(fail())

  ff <- .sbivml_pm_factor(
    pm$Prec,
    ord_stat,
    append_amd   = append_amd,
    check_factor = check_factor
  )
  if (is.null(ff)) return(fail(ord_stat))

  dP <- lapply(
    pm$dPrec_list,
    function(M) {
      if (is.null(M)) NULL else
        M[ff$ord_final, ff$ord_final, drop = FALSE]
    }
  )

  dU <- .sbivml_chol_upper_derivative_list(
    dP,
    ff$U,
    rho_index = pm$base$idx_rho_raw,
    rho       = pm$base$pp$rho
  )
  if (is.null(dU)) return(fail(ff$ord_final))

  rec <- .sbivml_me_pm_grad_from_U(
    lower   = pm$lower[ff$ord_final],
    upper   = pm$upper[ff$ord_final],
    dlower  = pm$dlower[ff$ord_final, , drop = FALSE],
    dupper  = pm$dupper[ff$ord_final, , drop = FALSE],
    U       = ff$U,
    dU_list = dU
  )

  if (!is.finite(rec$logp) || any(!is.finite(rec$grad))) {
    return(fail(ff$ord_final))
  }

  list(
    logLik            = as.numeric(pm$base$log_fx + rec$logp),
    gradient          = as.numeric(pm$base$g_fx + rec$grad),
    order             = ff$ord_final,
    ord_stat          = ff$ord_stat,
    ord_fill_relative = ff$ord_fill_relative,
    rule              = rule,
    engine            = "ME_PM",
    amd_applied       = append_amd,
    amd_nontrivial    = ff$amd_nontrivial,
    nnz_U             = ff$nnz_U,
    nnz_P_upper       = ff$nnz_P_upper,
    fill_ratio        = if (ff$nnz_P_upper > 0) ff$nnz_U / ff$nnz_P_upper else NA_real_
  )
}

.sbivml_eval_me_vc <- function(par, y, X, xend, Z, problem,
                              rule = c("N", "M"),
                              fixed_order = NULL) {
  rule <- match.arg(rule)
  obj <- .sbivml_build_me_vc_objects(par, y, X, xend, Z, problem)

  fail <- function(order = NULL) {
    list(
      logLik            = -Inf,
      gradient          = rep(NA_real_, length(par)),
      order             = order,
      ord_stat          = NULL,
      ord_fill_relative = NULL,
      rule              = rule,
      engine            = "ME_VC",
      amd_applied       = FALSE,
      amd_nontrivial    = FALSE
    )
  }

  if (is.null(obj)) return(fail())
  base <- obj$base
  n <- base$n

  if (!is.null(fixed_order)) {
    if (!.sbivml_valid_perm(fixed_order, n)) return(fail())
    ord_final <- as.integer(fixed_order)
    ord_stat <- ord_final
  } else if (rule == "N") {
    ord_final <- seq_len(n)
    ord_stat <- ord_final
  } else {
    ord_stat <- .sbivml_mg_me_order(
      obj$lower,
      obj$upper,
      diag(base$Omega),
      precision_storage = FALSE
    )
    if (is.null(ord_stat) || !.sbivml_valid_perm(ord_stat, n)) return(fail())
    ord_final <- as.integer(ord_stat)
  }

  rec <- .sbivml_me_vc_grad(
    lower = obj$lower[ord_final],
    upper = obj$upper[ord_final],
    Omega = base$Omega[ord_final, ord_final, drop = FALSE],
    dlower = obj$dlower[ord_final, , drop = FALSE],
    dupper = obj$dupper[ord_final, , drop = FALSE],
    dOmega_list = lapply(
      base$dOmega_list,
      function(M) {
        if (is.null(M)) NULL else M[ord_final, ord_final, drop = FALSE]
      }
    ),
    rho_index = base$idx_rho_raw,
    rho = base$pp$rho
  )

  if (!is.finite(rec$logp) || any(!is.finite(rec$grad))) {
    return(fail(ord_final))
  }

  list(
    logLik = as.numeric(base$log_fx + rec$logp),
    gradient = as.numeric(base$g_fx + rec$grad),
    order = as.integer(ord_final),
    ord_stat = as.integer(ord_stat),
    ord_fill_relative = seq_len(n),
    rule = rule,
    engine = "ME_VC",
    amd_applied = FALSE,
    amd_nontrivial = FALSE
  )
}

.sbivml_eval_ris <- function(par, y, X, xend, Z, problem, draws,
                            engine = c("RIS_PM", "RIS_VC"),
                            fixed_order = NULL) {
  engine <- match.arg(engine)
  ee <- if (engine == "RIS_PM") "pm" else "vc"

  base <- .sbivml_joint_base(
    par,
    y = y,
    X = X,
    xend = xend,
    Z = Z,
    W = problem$W,
    need_pm = ee == "pm",
    need_vc = ee == "vc",
    pm_cache = problem$pm_cache
  )

  fail <- function(order = fixed_order) {
    list(
      logLik = -Inf,
      gradient = rep(NA_real_, length(par)),
      order = order,
      ord_stat = order,
      ord_fill_relative = if (!is.null(order)) seq_along(order) else NULL,
      rule = "M",
      engine = engine,
      amd_applied = FALSE,
      amd_nontrivial = FALSE
    )
  }

  if (is.null(base)) return(fail())

  q <- 2 * as.integer(y) - 1
  s <- as.numeric(q * base$mu)
  ds <- base$dmu * q

  if (is.null(fixed_order)) {
    diagOmega <- if (ee == "pm") {
      .sbivml_exact_diag_omega(base)
    } else {
      diag(base$Omega)
    }
    if (is.null(diagOmega)) return(fail())

    ord <- .sbivml_mg_ris_order(
      s,
      diagOmega,
      precision_storage = identical(ee, "pm")
    )
  } else {
    ord <- as.integer(fixed_order)
  }

  if (is.null(ord) || !.sbivml_valid_perm(ord, base$n)) return(fail(ord))

  q_ord <- q[ord]

  if (ee == "pm") {
    Prec_ord <- .sbivml_sign_adjust(
      base$Prec[ord, ord, drop = FALSE],
      q_ord
    )
    dPrec_ord <- lapply(
      base$dPrec_list,
      function(M) {
        if (is.null(M)) NULL else
          .sbivml_sign_adjust(M[ord, ord, drop = FALSE], q_ord)
      }
    )

    ff <- .sbivml_chol_upper(
      Prec_ord,
      amd = FALSE,
      check_factor = FALSE
    )

    if (is.null(ff) || !identical(ff$perm, seq_len(base$n))) {
      return(fail(ord))
    }

    dU <- .sbivml_chol_upper_derivative_list(
      dPrec_ord,
      ff$U,
      rho_index = base$idx_rho_raw,
      rho = base$pp$rho
    )
    if (is.null(dU)) return(fail(ord))

    rec <- .sbivml_ris_pm_grad_from_U(
      s = s[ord],
      ds = ds[ord, , drop = FALSE],
      U = ff$U,
      dU_list = dU,
      draws = draws[ord, , drop = FALSE]
    )
    nnz_U <- ff$nnz_U
  } else {
    sign_ord <- tcrossprod(q_ord, q_ord)
    Omega_ord <- base$Omega[ord, ord, drop = FALSE] * sign_ord
    dOmega_ord <- lapply(
      base$dOmega_list,
      function(M) {
        if (is.null(M)) NULL else M[ord, ord, drop = FALSE] * sign_ord
      }
    )

    rec <- .sbivml_ris_vc_grad(
      s = s[ord],
      ds = ds[ord, , drop = FALSE],
      Omega = Omega_ord,
      dOmega_list = dOmega_ord,
      draws = draws[ord, , drop = FALSE],
      rho_index = base$idx_rho_raw,
      rho = base$pp$rho
    )
    nnz_U <- NA_integer_
  }

  if (!is.finite(rec$logp) || any(!is.finite(rec$grad))) {
    return(fail(ord))
  }

  list(
    logLik = as.numeric(base$log_fx + rec$logp),
    gradient = as.numeric(base$g_fx + rec$grad),
    order = as.integer(ord),
    ord_stat = as.integer(ord),
    ord_fill_relative = seq_len(base$n),
    rule = "M",
    engine = engine,
    amd_applied = FALSE,
    amd_nontrivial = FALSE,
    nnz_U = nnz_U
  )
}

## ========================================== -
## Generic optimizer and fixed-order Hessian ----
## ========================================== -

.sbivml_optimize_joint <- function(start, bounds, evaluator, fixed_builder,
                                  label, X, Z,
                                  maxit = 800L, factr = 1e7, pgtol = 1e-6,
                                  compute_hessian = TRUE) {
  cache         <- new.env(parent = emptyenv())
  cache$par     <- NULL
  cache$ans     <- NULL
  n_eval_unique <- 0L
  n_invalid     <- 0L

  eval_cached <- function(par) {
    if (!is.null(cache$par) &&
        length(cache$par) == length(par) &&
        max(abs(cache$par - par)) < 1e-14) {
      return(cache$ans)
    }

    ans <- evaluator(par)
    n_eval_unique <<- n_eval_unique + 1L

    valid <- is.list(ans) &&
      is.finite(ans$logLik) &&
      !is.null(ans$gradient) &&
      length(ans$gradient) == length(par) &&
      all(is.finite(ans$gradient))

    if (!valid) n_invalid <<- n_invalid + 1L

    cache$par <- as.numeric(par)
    cache$ans <- ans
    ans
  }

  fn <- function(par) {
    ans <- eval_cached(par)
    if (!is.finite(ans$logLik)) return(1e100)
    -ans$logLik
  }

  gr <- function(par) {
    ans <- eval_cached(par)
    if (!is.finite(ans$logLik) ||
        is.null(ans$gradient) ||
        length(ans$gradient) != length(par) ||
        any(!is.finite(ans$gradient))) {
      stop("Invalid criterion/gradient during ", label, ".")
    }
    -ans$gradient
  }

  t0  <- proc.time()[["elapsed"]]
  opt <- try(stats::optim(par     = start,
                          fn      = fn,
                          gr      = gr,
                          method  = "L-BFGS-B",
                          lower   = bounds$lower,
                          upper   = bounds$upper,
                          control = list(maxit = maxit,
                                         factr = factr,
                                         pgtol = pgtol)),
             silent = TRUE)
  fit_elapsed <- proc.time()[["elapsed"]] - t0

  fail <- function(code, msg, par = rep(NA_real_, length(start))) {
    list(
      fit_ok          = FALSE,
      optimizer_clean = FALSE,
      convergence     = code,
      message         = msg,
      par             = par,
      logLik          = NA_real_,
      vc_ok           = FALSE,
      hessian_valid   = FALSE,
      fit_elapsed     = fit_elapsed,
      hessian_elapsed = NA_real_,
      bounds          = bounds,
      start           = start
    )
  }

  if (inherits(opt, "try-error")) {
    return(fail(98L, as.character(opt)))
  }

  final <- try(eval_cached(opt$par), silent = TRUE)
  if (inherits(final, "try-error") ||
      !is.list(final) ||
      !is.finite(final$logLik) ||
      any(!is.finite(final$gradient)) ||
      is.null(final$order)) {
    return(fail(
      97L,
      "Optimizer returned an invalid final criterion, gradient, or ordering.",
      opt$par
    ))
  }

  fixed_eval <- fixed_builder(final$order)
  if (!is.function(fixed_eval)) {
    return(fail(
      96L,
      "Could not construct fixed-order endpoint evaluator.",
      opt$par
    ))
  }

  H <- NULL
  Vopt <- NULL
  Vstruct <- NULL
  se_struct <- NULL
  vc_ok <- FALSE
  hessian_pd <- FALSE
  hessian_min_eig <- NA_real_
  hessian_rcond <- NA_real_
  hessian_elapsed <- 0

  if (isTRUE(compute_hessian)) {
    hcache <- new.env(parent = emptyenv())
    hcache$par <- NULL
    hcache$ans <- NULL

    heval <- function(par) {
      if (!is.null(hcache$par) &&
          length(hcache$par) == length(par) &&
          max(abs(hcache$par - par)) < 1e-14) {
        return(hcache$ans)
      }
      ans <- fixed_eval(par)
      hcache$par <- as.numeric(par)
      hcache$ans <- ans
      ans
    }

    hfn <- function(par) {
      ans <- heval(par)
      if (!is.finite(ans$logLik)) return(1e100)
      -ans$logLik
    }

    hgr <- function(par) {
      ans <- heval(par)
      if (!is.finite(ans$logLik) || any(!is.finite(ans$gradient))) {
        stop("Invalid fixed-order score during Hessian for ", label)
      }
      -ans$gradient
    }

    th0 <- proc.time()[["elapsed"]]
    Hraw <- try(
      stats::optimHess(opt$par, fn = hfn, gr = hgr),
      silent = TRUE
    )
    hessian_elapsed <- proc.time()[["elapsed"]] - th0

    if (!inherits(Hraw, "try-error") &&
        is.matrix(Hraw) &&
        all(dim(Hraw) == c(length(start), length(start))) &&
        all(is.finite(Hraw))) {
      H <- 0.5 * (Hraw + t(Hraw))
      ee <- try(
        eigen(H, symmetric = TRUE, only.values = TRUE)$values,
        silent = TRUE
      )

      if (!inherits(ee, "try-error") && all(is.finite(ee))) {
        hessian_min_eig <- min(ee)
        tol_pd <- 1e-8 * max(1, max(abs(ee)))
        hessian_pd <- hessian_min_eig > tol_pd
      }

      hessian_rcond <- tryCatch(rcond(H), error = function(e) NA_real_)

      if (isTRUE(hessian_pd)) {
        RR <- try(chol(H), silent = TRUE)
        if (!inherits(RR, "try-error")) {
          Vopt0 <- try(chol2inv(RR), silent = TRUE)
          if (!inherits(Vopt0, "try-error") && all(is.finite(Vopt0))) {
            J <- .sbivml_structural_jacobian(opt$par, X = X, Z = Z)
            VV <- J %*% Vopt0 %*% t(J)
            VV <- 0.5 * (VV + t(VV))
            dd <- diag(VV)

            if (all(is.finite(dd)) && all(dd > 0)) {
              Vopt <- Vopt0
              Vstruct <- VV
              se_struct <- sqrt(dd)
              names(se_struct) <- rownames(J)
              rownames(Vstruct) <- colnames(Vstruct) <- rownames(J)
              vc_ok <- TRUE
            }
          }
        }
      }
    }
  }

  score <- as.numeric(final$gradient)
  names(score) <- names(start)
  pscore <- .sbivml_projected_score(
    opt$par, score, bounds$lower, bounds$upper
  )
  bflags <- .sbivml_boundary_flags(
    opt$par, bounds$lower, bounds$upper
  )

  optimizer_clean <- isTRUE(opt$convergence == 0L)

  list(
    fit_ok = TRUE,
    optimizer_clean = optimizer_clean,
    converged = optimizer_clean,
    estimator = label,
    convergence = as.integer(opt$convergence),
    message = as.character(opt$message),
    fit_elapsed = fit_elapsed,
    hessian_elapsed = hessian_elapsed,
    total_elapsed = fit_elapsed + hessian_elapsed,
    counts = opt$counts,
    par = setNames(as.numeric(opt$par), names(start)),
    coef_structural = .sbivml_structural_vector(opt$par, X = X, Z = Z),
    logLik = final$logLik,
    score = score,
    score_norm = sqrt(sum(score^2)),
    score_maxabs = max(abs(score)),
    projected_score = pscore,
    projected_score_norm = sqrt(sum(pscore^2)),
    projected_score_maxabs = max(abs(pscore)),
    boundary_flags = bflags,
    any_boundary = any(bflags),
    final_order = final$order,
    final_order_signature = .sbivml_perm_signature(final$order),
    final_ord_stat = final$ord_stat,
    final_ord_fill_relative = final$ord_fill_relative,
    final_amd_applied = isTRUE(final$amd_applied),
    final_amd_nontrivial = isTRUE(final$amd_nontrivial),
    final_nnz_U = if (!is.null(final$nnz_U)) final$nnz_U else NA_integer_,
    final_nnz_P_upper = if (!is.null(final$nnz_P_upper)) final$nnz_P_upper else NA_integer_,
    final_fill_ratio = if (!is.null(final$fill_ratio)) final$fill_ratio else NA_real_,
    n_eval_unique = n_eval_unique,
    n_invalid = n_invalid,
    hessian = H,
    hessian_fixed_order = TRUE,
    hessian_pd = hessian_pd,
    hessian_min_eig = hessian_min_eig,
    hessian_rcond = hessian_rcond,
    vcov_optimizer = if (isTRUE(vc_ok)) Vopt else NULL,
    vcov_structural = if (isTRUE(vc_ok)) Vstruct else NULL,
    se_structural = if (isTRUE(vc_ok)) se_struct else NULL,
    vc_ok = isTRUE(vc_ok),
    hessian_valid = isTRUE(vc_ok),
    bounds = bounds,
    start = start,
    final = final
  )
}

.sbivml_fit_joint <- function(engine, rule,
                             y, X, xend, Z, problem,
                             draws = NULL,
                             start = NULL,
                             maxit = 800L,
                             factr = 1e7,
                             pgtol = 1e-6,
                             compute_hessian = TRUE) {
  valid <- (
    (engine %in% c("ME_PM", "ME_VC") && rule %in% c("N", "M")) ||
    (engine %in% c("RIS_PM", "RIS_VC") && rule == "M")
  )
  if (!valid) stop("Unsupported estimator combination: ", engine, "_", rule)

  if (engine %in% c("RIS_PM", "RIS_VC") && is.null(draws)) {
    stop("RIS requires simulation draws.")
  }

  bounds <- .sbivml_joint_bounds(problem, X = X, Z = Z)
  if (is.null(start)) {
    start <- .sbivml_make_start(y, X, xend, Z, bounds, problem)
  }

  evaluator <- switch(
    engine,
    ME_PM = function(par) {.sbivml_eval_me_pm(par, y, X, xend, Z, problem, rule = rule)},
    ME_VC = function(par) {.sbivml_eval_me_vc(par, y, X, xend, Z, problem, rule = rule)},
    RIS_PM = function(par) {.sbivml_eval_ris(par, y, X, xend, Z, problem, draws, engine = "RIS_PM")},
    RIS_VC = function(par) {.sbivml_eval_ris(par, y, X, xend, Z, problem, draws, engine = "RIS_VC")}
  )

  fixed_builder <- switch(
    engine,
    ME_PM  = function(ord) {function(par) {.sbivml_eval_me_pm(par, y, X, xend, Z, problem, rule = rule, fixed_order = ord)}},
    ME_VC  = function(ord) {function(par) {.sbivml_eval_me_vc(par, y, X, xend, Z, problem, rule = rule, fixed_order = ord)}},
    RIS_PM = function(ord) {function(par) {.sbivml_eval_ris(par, y, X, xend, Z, problem, draws, engine = "RIS_PM", fixed_order = ord)}},
    RIS_VC = function(ord) {function(par) {.sbivml_eval_ris(par, y, X, xend, Z, problem, draws, engine = "RIS_VC", fixed_order = ord)}}
  )

  label <- if (engine == "ME_PM" && rule == "M") {"ME_PM_MD"} else {paste(engine, rule, sep = "_")}

  fit <- .sbivml_optimize_joint(
    start           = start,
    bounds          = bounds,
    evaluator       = evaluator,
    fixed_builder   = fixed_builder,
    label           = label,
    X               = X,
    Z               = Z,
    maxit           = maxit,
    factr           = factr,
    pgtol           = pgtol,
    compute_hessian = compute_hessian
  )

  if (engine %in% c("RIS_PM", "RIS_VC")) {fit$ris_draws <- ncol(draws)}
  fit
}

## ===================================================== -
## Operational model-based sandwich covariance (ME only) ----
## ===================================================== -

.sbivml_make_sandwich_draws <- function(n, B = 500L, seed = 123L,
                                       preserve_seed = TRUE) {
  if (B < 1L) stop("B must be positive.")

  old_exists <- exists(
    ".Random.seed", envir = .GlobalEnv, inherits = FALSE
  )
  if (isTRUE(preserve_seed)) {
    old <- if (old_exists) get(".Random.seed", envir = .GlobalEnv) else NULL
    on.exit({
      if (old_exists) {
        assign(".Random.seed", old, envir = .GlobalEnv)
      } else if (exists(".Random.seed", envir = .GlobalEnv, inherits = FALSE)) {
        rm(".Random.seed", envir = .GlobalEnv)
      }
    }, add = TRUE)
  }

  set.seed(seed)
  raw <- matrix(stats::rnorm(2L * n * B), nrow = 2L * n, ncol = B)
  list(z_v   = raw[seq_len(n), , drop = FALSE], 
       z_eta = raw[n + seq_len(n), , drop = FALSE],
       seed  = as.integer(seed))
}

.sbivml_simulate_conditional_batch <- function(par, X, Z, problem,
                                              endog_col, draws) {
  pp <- .sbivml_read_parameters(par, X, Z)
  n <- nrow(X)
  B <- ncol(draws$z_v)

  if (nrow(draws$z_v) != n || nrow(draws$z_eta) != n ||
      ncol(draws$z_eta) != B) {
    stop("Invalid sandwich draw dimensions.")
  }
  if (length(endog_col) != 1L || is.na(endog_col) ||
      endog_col < 1L || endog_col > ncol(X)) {
    stop("Invalid endogenous-regressor column index.")
  }
  if (!(pp$lambda > problem$lambda_space$lower &&
        pp$lambda < problem$lambda_space$upper)) {
    stop("Sandwich simulation lambda lies outside the admissible interval.")
  }

  V    <- pp$sigma_v * draws$z_v
  E    <- pp$rho * draws$z_v + sqrt(1 - pp$rho^2) * draws$z_eta
  zpi  <- as.numeric(Z %*% pp$pi)
  Xend <- zpi + V

  beta_end <- pp$beta[endog_col]
  if (ncol(X) == 1L) {
    fixed_rhs <- rep(0, n)
  } else {
    fixed_rhs <- as.numeric(X[, -endog_col, drop = FALSE] %*% pp$beta[-endog_col])
  }
  RHS <- fixed_rhs + beta_end * Xend + E

  A        <- Matrix::drop0(problem$pm_cache$I - pp$lambda * problem$W)
  A_factor <- .sbivml_factor_A(A)
  Ystar0   <- .sbivml_solve_A(A, RHS, factor = A_factor)
  Ystar    <- if (is.null(Ystar0)) NULL else tryCatch(as.matrix(Ystar0), error = function(e) NULL)
  if (is.null(Ystar) || any(!is.finite(Ystar))) {return(NULL)}

  list(y = (Ystar > 0) * 1, xend = Xend)
}

.sbivml_fixed_me_score <- function(par, engine, rule, y, X, xend, Z,
                                  problem, order) {
  ans <- switch(engine, 
                ME_PM = .sbivml_eval_me_pm(par, y, X, xend, Z, problem,
                                          rule = rule, fixed_order = order),
                ME_VC = .sbivml_eval_me_vc(par, y, X, xend, Z, problem,
                                          rule = rule, fixed_order = order),
                stop("Operational sandwich is implemented for ME only.")
  )

  if (!is.finite(ans$logLik) || length(ans$gradient) != length(par) || 
      any(!is.finite(ans$gradient))) {return(NULL)}
  as.numeric(ans$gradient)
}

.sbivml_operational_sandwich <- function(fit, engine, rule,
                                        X, xend, Z, problem,
                                        endog_col, draws) {
  if (!engine %in% c("ME_PM", "ME_VC")) {
    return(list(ok = FALSE, reason = "operational sandwich is available for ME only"))
  }
  if (!isTRUE(fit$fit_ok) || is.null(fit$par) ||
      is.null(fit$final_order) || is.null(fit$hessian) ||
      !isTRUE(fit$hessian_valid) || is.null(fit$vcov_optimizer)) {
    return(list(ok = FALSE, reason = "fit/order/positive-definite Hessian unavailable"))
  }

  p <- length(fit$par)
  B <- ncol(draws$z_v)
  if (B <= p + 2L) {
    return(list(ok = FALSE, 
                reason = "R must exceed the optimizer parameter dimension + 2",
                n_inner_requested = B))
  }

  sim <- try(
    .sbivml_simulate_conditional_batch(
      fit$par, X, Z, problem, endog_col, draws
    ),
    silent = TRUE
  )
  if (inherits(sim, "try-error") || is.null(sim)) {
    return(list(ok = FALSE, reason = "conditional sandwich simulation failed"))
  }

  scores <- matrix(NA_real_, nrow = B, ncol = p)
  valid  <- logical(B)
  t0     <- proc.time()[["elapsed"]]

  for (b in seq_len(B)) {
    Xb <- X
    Xb[, endog_col] <- sim$xend[, b]
    sc <- try(.sbivml_fixed_me_score(fit$par, engine, rule, 
                                    y       = sim$y[, b],
                                    X       = Xb,
                                    xend    = sim$xend[, b],
                                    Z       = Z,
                                    problem = problem,
                                    order   = fit$final_order),
              silent = TRUE)
    if (inherits(sc, "try-error") || is.null(sc) ||
        length(sc) != p || any(!is.finite(sc))) {next}
    scores[b, ] <- sc
    valid[b]    <- TRUE
  }
  elapsed <- proc.time()[["elapsed"]] - t0

  S <- scores[valid, , drop = FALSE]
  nvalid <- nrow(S)
  if (nvalid <= p + 2L) {
    return(list(
      ok = FALSE,
      reason = "too few valid inner score draws",
      n_inner_requested = B,
      n_inner_valid = nvalid,
      elapsed = elapsed
    ))
  }

  K <- stats::cov(S)
  if (any(!is.finite(K))) {
    return(list(
      ok = FALSE, reason = "non-finite sandwich score covariance",
      n_inner_requested = B, n_inner_valid = nvalid, elapsed = elapsed
    ))
  }
  K <- 0.5 * (K + t(K))

  H <- 0.5 * (fit$hessian + t(fit$hessian))
  Hinv <- fit$vcov_optimizer
  if (is.null(Hinv) || any(!is.finite(Hinv))) {
    return(list(
      ok = FALSE, reason = "inverse Hessian unavailable",
      n_inner_requested = B, n_inner_valid = nvalid, elapsed = elapsed
    ))
  }

  Vopt <- Hinv %*% K %*% Hinv
  Vopt <- 0.5 * (Vopt + t(Vopt))

  ## Same scaling identity in the MC experiment of the paper
  n <- nrow(Z)
  Jn <- H / n
  Kn <- K / n
  Vnorm0 <- try(solve(Jn), silent = TRUE)
  if (inherits(Vnorm0, "try-error")) {
    return(list(
      ok = FALSE, reason = "normalized Hessian solve failed",
      n_inner_requested = B, n_inner_valid = nvalid, elapsed = elapsed
    ))
  }
  Vnorm <- (Vnorm0 %*% Kn %*% t(Vnorm0)) / n
  scerr <- max(abs(Vopt - Vnorm)) / max(1, max(abs(Vopt)), max(abs(Vnorm)))
  if (!is.finite(scerr) || scerr > 1e-10) {
    return(list(
      ok = FALSE, reason = "sandwich n-scaling identity failed",
      n_inner_requested = B, n_inner_valid = nvalid,
      elapsed = elapsed, scaling_identity_error = scerr
    ))
  }

  J <- .sbivml_structural_jacobian(fit$par, X, Z)
  Vstruct <- J %*% Vopt %*% t(J)
  Vstruct <- 0.5 * (Vstruct + t(Vstruct))
  rownames(Vstruct) <- colnames(Vstruct) <- rownames(J)
  dd <- diag(Vstruct)
  if (any(!is.finite(dd)) || any(dd <= 0)) {
    return(list(
      ok = FALSE, reason = "invalid structural sandwich diagonal",
      n_inner_requested = B, n_inner_valid = nvalid,
      elapsed = elapsed, scaling_identity_error = scerr
    ))
  }

  se <- sqrt(dd)
  names(se) <- rownames(J)

  list(
    ok = TRUE,
    n_inner_requested = B,
    n_inner_valid = nvalid,
    inner_valid_rate = nvalid / B,
    elapsed = elapsed,
    mean_score = colMeans(S),
    K_optimizer = K,
    vcov_optimizer = Vopt,
    vcov_structural = Vstruct,
    se_structural = se,
    K_min_eig = tryCatch(
      min(eigen(K, symmetric = TRUE, only.values = TRUE)$values),
      error = function(e) NA_real_
    ),
    K_rcond = tryCatch(rcond(K), error = function(e) NA_real_),
    scaling_identity_error = scerr
  )
}

## =========== -
## S3 methods ----
## =========== -

#' @rdname sbinary_iv_ml
#' @export
coef.binivml <- function(object, ...) {
  object$coefficients
}


#' @rdname sbinary_iv_ml
#' @method vcov binivml
#' @export
vcov.binivml <- function(object,
                        vce = c("hessian", "sandwich"),
                        R = 500L,
                        seed = 123L,
                        ...) {
  vce <- match.arg(vce)

  if (vce == "hessian") {
    V <- object$opt$vcov_structural
    if (is.null(V) || !isTRUE(object$opt$hessian_valid)) {
      stop(
        "A valid positive-definite fixed-order Hessian is not available. ",
        "Re-estimate with hessian = TRUE and inspect the optimizer diagnostics."
      )
    }
    V <- as.matrix(V)
    attr(V, "vce") <- "hessian"
    return(V)
  }

  if (!identical(object$method, "ME")) {
    stop(
      "The operational sandwich covariance is currently implemented ",
      "for method = 'ME' only."
    )
  }

  if (!is.numeric(R) || length(R) != 1L || !is.finite(R) || R < 1) {
    stop("'R' must be a positive integer.")
  }
  R <- as.integer(R)

  if (!is.numeric(seed) || length(seed) != 1L || !is.finite(seed)) {
    stop("'seed' must be a finite integer.")
  }
  seed <- as.integer(seed)

  if (!isTRUE(object$opt$hessian_valid) ||
      is.null(object$opt$hessian) ||
      is.null(object$opt$vcov_optimizer)) {
    stop(
      "Sandwich covariance estimation requires a valid positive-definite ",
      "fixed-order Hessian. Re-estimate with hessian = TRUE."
    )
  }

  p <- length(object$opt$par)
  if (R <= p + 2L) {
    stop(
      "'R' must exceed the optimizer parameter dimension + 2. ",
      "For this model use R > ", p + 2L, "."
    )
  }

  draws <- .sbivml_make_sandwich_draws(
    n             = length(object$y),
    B             = R,
    seed          = seed,
    preserve_seed = TRUE
  )

  sand <- .sbivml_operational_sandwich(
    fit       = object$opt,
    engine    = object$engine,
    rule      = object$rule,
    X         = object$X,
    xend      = object$xend,
    Z         = object$Z,
    problem   = object$problem,
    endog_col = object$endog_col,
    draws     = draws
  )

  if (!isTRUE(sand$ok)) {
    stop("Sandwich covariance estimation failed: ", sand$reason)
  }

  V <- as.matrix(sand$vcov_structural)
  attr(V, "vce") <- "sandwich"
  attr(V, "R") <- R
  attr(V, "seed") <- seed
  attr(V, "n_inner_valid") <- sand$n_inner_valid
  attr(V, "inner_valid_rate") <- sand$inner_valid_rate
  attr(V, "scaling_identity_error") <- sand$scaling_identity_error
  attr(V, "elapsed") <- sand$elapsed
  V
}

#' @rdname sbinary_iv_ml
#' @export
logLik.binivml <- function(object, ...) {
  structure(object$logLik, df = length(object$coefficients), 
            nobs = length(object$y), class = "logLik")
}

#' @rdname sbinary_iv_ml
#' @method terms binivml
#' @export
terms.binivml <- function(x, ...) {
  formula(x$formula)
}

#' @rdname sbinary_iv_ml
#' @method print binivml
#' @export
print.binivml <- function(x, ...) {
  cat("Spatial binary probit with a continuous endogenous regressor\n")
  cat(
    "Method: ", x$method,
    " | Cholesky: ", x$varcov,
    " | ordering: ", x$ordering,
    "\n", sep = ""
  )
  if (identical(x$method, "RIS")) {
    cat("RIS draws: ", x$R, "\n", sep = "")
  }
  cat(
    "Convergence code: ", x$opt$convergence,
    " | Log-Likelihood: ", format(x$logLik, digits = 8),
    "\n", sep = ""
  )
  print(x$coefficients)
  invisible(x)
}

#' @rdname sbinary_iv_ml
#' @method summary binivml
#' @export
summary.binivml <- function(object,
                           vce  = c("hessian", "sandwich"),
                           R    = 500L,
                           seed = 123L,
                           ...) {
  vce <- match.arg(vce)

  b  <- coef(object)
  V  <- vcov(object, vce = vce, R = R, seed = seed, ...)
  se <- sqrt(diag(V))
  z  <- b / se
  p  <- 2 * stats::pnorm(-abs(z))
  tab <- cbind(Estimate = b, `Std. error` = se, `z value` = z, `Pr(> z)` = p)

  out <- list(
    call = object$call,
    method = object$method,
    varcov = object$varcov,
    vce = vce,
    ordering = object$ordering,
    R = object$R,
    N = length(object$y),
    endog = object$endog,
    logLik = object$logLik,
    convergence = object$opt$convergence,
    message = object$opt$message,
    coefficients = tab,
    hessian_valid = object$opt$hessian_valid,
    optimizer_clean = object$opt$optimizer_clean,
    sandwich_R = if (vce == "sandwich") attr(V, "R") else NULL,
    sandwich_seed = if (vce == "sandwich") attr(V, "seed") else NULL,
    sandwich_n_valid = if (vce == "sandwich") attr(V, "n_inner_valid") else NULL,
    sandwich_valid_rate = if (vce == "sandwich") attr(V, "inner_valid_rate") else NULL,
    sandwich_scaling_error = if (vce == "sandwich") attr(V, "scaling_identity_error") else NULL
  )
  class(out) <- "summary.binivml"
  out
}

#' @rdname sbinary_iv_ml
#' @method print summary.binivml
#' @export
print.summary.binivml <- function(x,
                                 digits = max(3, getOption("digits") - 2),
                                 ...) {
  cat("--------------------------------------------\n")
  cat("Spatial binary probit with endogenous regressor\n")
  cat("Endogenous variable: ", x$endog, "\n", sep = "")
  cat(
    "Method: ", x$method,
    " | Cholesky: ", x$varcov,
    " | ordering: ", x$ordering,
    "\n", sep = ""
  )
  if (identical(x$method, "RIS")) {
    cat("RIS draws: ", x$R, "\n", sep = "")
  }
  cat("Standard errors: ", x$vce, "\n", sep = "")
  if (identical(x$vce, "sandwich")) {
    cat(
      "Sandwich inner draws: ", x$sandwich_R,
      " | valid: ", x$sandwich_n_valid,
      " (", format(100 * x$sandwich_valid_rate, digits = 4), "%)\n",
      sep = ""
    )
  }
  cat("Sample size: ", x$N, "\n", sep = "")
  cat("Convergence code: ", x$convergence, "\n", sep = "")
  cat("Log-Likelihood: ", format(x$logLik, digits = digits), "\n", sep = "")
  if (!isTRUE(x$optimizer_clean)) {
    cat("Optimizer message: ", x$message, "\n", sep = "")
  }
  if (!isTRUE(x$hessian_valid)) {
    cat("Note: a valid positive-definite Hessian is not available.\n")
  }
  cat("Estimates:\n")
  stats::printCoefmat(x$coefficients, digits = digits)
  cat("--------------------------------------------\n")
  invisible(x)
}
